
// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Nov 17 2020 14:05:34 EST (Nov 17 2020 19:05:34 UTC)

module test_mux_16_4(data0, data1, data2, data3, ctrl, out);
  input [15:0] data0, data1, data2, data3;
  input [3:0] ctrl;
  output [15:0] out;
  wire [15:0] data0, data1, data2, data3;
  wire [3:0] ctrl;
  wire [15:0] out;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  NAND2X1 g283(.A (n_31), .B (n_12), .Y (out[11]));
  NAND2X1 g273(.A (n_19), .B (n_15), .Y (out[14]));
  NAND2X1 g282(.A (n_1), .B (n_2), .Y (out[13]));
  NAND2X1 g274(.A (n_11), .B (n_20), .Y (out[12]));
  NAND2X1 g276(.A (n_6), .B (n_14), .Y (out[15]));
  NAND2X1 g285(.A (n_4), .B (n_30), .Y (out[10]));
  NAND2X1 g275(.A (n_28), .B (n_21), .Y (out[9]));
  NAND2X1 g279(.A (n_9), .B (n_23), .Y (out[8]));
  NAND2X1 g272(.A (n_27), .B (n_13), .Y (out[3]));
  NAND2X1 g280(.A (n_10), .B (n_8), .Y (out[6]));
  NAND2X1 g286(.A (n_7), .B (n_3), .Y (out[5]));
  NAND2X1 g287(.A (n_29), .B (n_26), .Y (out[4]));
  NAND2X1 g281(.A (n_18), .B (n_0), .Y (out[7]));
  NAND2X1 g277(.A (n_24), .B (n_17), .Y (out[2]));
  NAND2X1 g278(.A (n_5), .B (n_16), .Y (out[1]));
  NAND2X1 g284(.A (n_25), .B (n_22), .Y (out[0]));
  AOI22X1 g310(.A0 (data2[11]), .A1 (ctrl[2]), .B0 (data3[11]), .B1
       (ctrl[3]), .Y (n_31));
  AOI22X1 g289(.A0 (data0[10]), .A1 (ctrl[0]), .B0 (data1[10]), .B1
       (ctrl[1]), .Y (n_30));
  AOI22X1 g304(.A0 (data2[4]), .A1 (ctrl[2]), .B0 (data3[4]), .B1
       (ctrl[3]), .Y (n_29));
  AOI22X1 g296(.A0 (data2[9]), .A1 (ctrl[2]), .B0 (data3[9]), .B1
       (ctrl[3]), .Y (n_28));
  AOI22X1 g292(.A0 (data2[3]), .A1 (ctrl[2]), .B0 (data3[3]), .B1
       (ctrl[3]), .Y (n_27));
  AOI22X1 g290(.A0 (data0[4]), .A1 (ctrl[0]), .B0 (data1[4]), .B1
       (ctrl[1]), .Y (n_26));
  AOI22X1 g305(.A0 (data2[0]), .A1 (ctrl[2]), .B0 (data3[0]), .B1
       (ctrl[3]), .Y (n_25));
  AOI22X1 g297(.A0 (data2[2]), .A1 (ctrl[2]), .B0 (data3[2]), .B1
       (ctrl[3]), .Y (n_24));
  AOI22X1 g306(.A0 (data0[8]), .A1 (ctrl[0]), .B0 (data1[8]), .B1
       (ctrl[1]), .Y (n_23));
  AOI22X1 g307(.A0 (data0[0]), .A1 (ctrl[0]), .B0 (data1[0]), .B1
       (ctrl[1]), .Y (n_22));
  AOI22X1 g298(.A0 (data0[9]), .A1 (ctrl[0]), .B0 (data1[9]), .B1
       (ctrl[1]), .Y (n_21));
  AOI22X1 g308(.A0 (data0[12]), .A1 (ctrl[0]), .B0 (data1[12]), .B1
       (ctrl[1]), .Y (n_20));
  AOI22X1 g293(.A0 (data2[14]), .A1 (ctrl[2]), .B0 (data3[14]), .B1
       (ctrl[3]), .Y (n_19));
  AOI22X1 g309(.A0 (data2[7]), .A1 (ctrl[2]), .B0 (data3[7]), .B1
       (ctrl[3]), .Y (n_18));
  AOI22X1 g299(.A0 (data0[2]), .A1 (ctrl[0]), .B0 (data1[2]), .B1
       (ctrl[1]), .Y (n_17));
  AOI22X1 g288(.A0 (data0[1]), .A1 (ctrl[0]), .B0 (data1[1]), .B1
       (ctrl[1]), .Y (n_16));
  AOI22X1 g319(.A0 (data0[14]), .A1 (ctrl[0]), .B0 (data1[14]), .B1
       (ctrl[1]), .Y (n_15));
  AOI22X1 g291(.A0 (data0[15]), .A1 (ctrl[0]), .B0 (data1[15]), .B1
       (ctrl[1]), .Y (n_14));
  AOI22X1 g294(.A0 (data0[3]), .A1 (ctrl[0]), .B0 (data1[3]), .B1
       (ctrl[1]), .Y (n_13));
  AOI22X1 g312(.A0 (data0[11]), .A1 (ctrl[0]), .B0 (data1[11]), .B1
       (ctrl[1]), .Y (n_12));
  AOI22X1 g300(.A0 (data2[12]), .A1 (ctrl[2]), .B0 (data3[12]), .B1
       (ctrl[3]), .Y (n_11));
  AOI22X1 g313(.A0 (data1[6]), .A1 (ctrl[1]), .B0 (data2[6]), .B1
       (ctrl[2]), .Y (n_10));
  AOI22X1 g301(.A0 (data2[8]), .A1 (ctrl[2]), .B0 (data3[8]), .B1
       (ctrl[3]), .Y (n_9));
  AOI22X1 g314(.A0 (data0[6]), .A1 (ctrl[0]), .B0 (data3[6]), .B1
       (ctrl[3]), .Y (n_8));
  AOI22X1 g315(.A0 (data2[5]), .A1 (ctrl[2]), .B0 (data3[5]), .B1
       (ctrl[3]), .Y (n_7));
  AOI22X1 g295(.A0 (data2[15]), .A1 (ctrl[2]), .B0 (data3[15]), .B1
       (ctrl[3]), .Y (n_6));
  AOI22X1 g302(.A0 (data2[1]), .A1 (ctrl[2]), .B0 (data3[1]), .B1
       (ctrl[3]), .Y (n_5));
  AOI22X1 g316(.A0 (data2[10]), .A1 (ctrl[2]), .B0 (data3[10]), .B1
       (ctrl[3]), .Y (n_4));
  AOI22X1 g317(.A0 (data0[5]), .A1 (ctrl[0]), .B0 (data1[5]), .B1
       (ctrl[1]), .Y (n_3));
  AOI22X1 g303(.A0 (data0[13]), .A1 (ctrl[0]), .B0 (data1[13]), .B1
       (ctrl[1]), .Y (n_2));
  AOI22X1 g318(.A0 (data2[13]), .A1 (ctrl[2]), .B0 (data3[13]), .B1
       (ctrl[3]), .Y (n_1));
  AOI22X1 g311(.A0 (data0[7]), .A1 (ctrl[0]), .B0 (data1[7]), .B1
       (ctrl[1]), .Y (n_0));
endmodule

