// Generated by stratus_hls 17.20-p100  (88533.190925)
// Tue Nov 17 22:53:07 2020
// from dut.cc
#ifndef CYNTH_PART_dut_dut_rtl_h
#define CYNTH_PART_dut_dut_rtl_h

#include "systemc.h"
/* Include declarations of instantiated parts. */
#include "dut_RAM_8X8_1.h"


/* Declaration of the synthesized module. */
struct dut : public sc_module {
  sc_in<bool > clk;
  sc_in<bool > rst;
  sc_out<bool > din_busy;
  sc_in<bool > din_vld;
  sc_in<sc_uint<8> > din_data;
  sc_in<bool > dout_busy;
  sc_out<bool > dout_vld;
  sc_out<sc_uint<11> > dout_data;
  dut( sc_module_name name );
  SC_HAS_PROCESS(dut);
  sc_signal<bool > dout_m_req_m_prev_trig_req;
  sc_signal<sc_uint<1> > dut_Xor_1Ux1U_1U_4_9_out1;
  sc_signal<bool > dout_m_unacked_req;
  sc_signal<sc_uint<1> > dut_Or_1Ux1U_1U_4_10_out1;
  sc_signal<sc_uint<1> > dut_N_Muxb_1_2_0_4_1_out1;
  sc_signal<sc_uint<1> > dut_And_1Ux1U_1U_4_5_out1;
  sc_signal<sc_uint<1> > dut_Not_1U_1U_4_4_out1;
  sc_signal<sc_uint<1> > dut_Or_1Ux1U_1U_4_2_out1;
  sc_signal<bool > din_m_unvalidated_req;
  sc_signal<sc_uint<1> > dut_And_1Ux1U_1U_4_3_out1;
  sc_signal<sc_uint<5> > global_state_next;
  sc_signal<sc_int<4> > dut_Add_4Sx2S_5S_4_16_in2;
  sc_signal<sc_uint<1> > gs_ctrl5;
  sc_signal<sc_int<3> > dut_Add_3Sx2S_3S_4_13_in2;
  sc_signal<sc_uint<1> > gs_ctrl4;
  sc_signal<sc_uint<2> > gs_ctrl3;
  sc_signal<sc_uint<1> > gs_ctrl2;
  sc_signal<sc_uint<2> > gs_ctrl1;
  sc_signal<sc_uint<4> > gs_ctrl0;
  sc_signal<sc_int<3> > dut_Add_3Sx2S_3S_4_13_out1;
  sc_signal<sc_uint<1> > dut_LessThan_4Sx4S_1U_4_15_out1;
  sc_signal<sc_int<5> > dut_Add_4Sx2S_5S_4_16_out1;
  sc_signal<sc_int<4> > dut_Add_4Sx2S_4S_4_14_out1;
  sc_signal<sc_uint<5> > s_reg_12;
  sc_signal<sc_uint<1> > dut_Not_1U_1U_4_6_out1;
  sc_signal<sc_uint<1> > dut_And_1Ux1U_1U_4_11_out1;
  sc_signal<sc_uint<1> > dut_Not_1U_1U_4_12_out1;
  sc_signal<bool > dout_m_req_m_trig_req;
  sc_signal<bool > din_m_busy_req_0;
  sc_signal<sc_uint<11> > dut_Add_11Ux8U_11U_4_18_out1;
  sc_signal<sc_uint<1> > dut_LessThan_5Sx5S_1U_4_17_out1;
  sc_signal<sc_uint<5> > global_state;
  sc_signal<sc_uint<1> > stall0;
  sc_signal<sc_uint<8> > dut_RAM_8X8_1_my_array_1_DIN;
  sc_signal<sc_uint<1> > dut_RAM_8X8_1_my_array_1_CE;
  sc_signal<sc_uint<1> > dut_RAM_8X8_1_my_array_1_RW;
  sc_signal<sc_uint<3> > dut_RAM_8X8_1_my_array_1_in1;
  sc_signal<sc_uint<8> > dut_RAM_8X8_1_my_array_1_out1;
  dut_RAM_8X8_1 *dut_RAM_8X8_1_my_array_1;
  void drive_dout_data();
  void drive_din_m_busy_req_0();
  void drive_dout_m_req_m_trig_req();
  void drive_stall0();
  void drive_s_reg_12();
  void drive_dut_RAM_8X8_1_my_array_1_in1();
  void drive_dut_RAM_8X8_1_my_array_1_DIN();
  void drive_dut_RAM_8X8_1_my_array_1_CE();
  void drive_dut_RAM_8X8_1_my_array_1_RW();
  void drive_dut_Add_3Sx2S_3S_4_13_in2();
  void dut_Add_3Sx2S_3S_4_13();
  void dut_Add_4Sx2S_4S_4_14();
  void dut_LessThan_4Sx4S_1U_4_15();
  void drive_dut_Add_4Sx2S_5S_4_16_in2();
  void dut_Add_4Sx2S_5S_4_16();
  void dut_LessThan_5Sx5S_1U_4_17();
  void dut_Add_11Ux8U_11U_4_18();
  void drive_global_state();
  void drive_global_state_next();
  void drive_gs_ctrl0();
  void drive_gs_ctrl1();
  void drive_gs_ctrl2();
  void drive_gs_ctrl3();
  void drive_gs_ctrl4();
  void drive_gs_ctrl5();
  void drive_din_busy();
  void dut_Or_1Ux1U_1U_4_2();
  void dut_And_1Ux1U_1U_4_3();
  void dut_Not_1U_1U_4_4();
  void dut_And_1Ux1U_1U_4_5();
  void dut_Not_1U_1U_4_6();
  void drive_din_m_unvalidated_req();
  void dut_N_Muxb_1_2_0_4_1();
  void drive_dout_vld();
  void dut_Or_1Ux1U_1U_4_10();
  void drive_dout_m_unacked_req();
  void dut_And_1Ux1U_1U_4_11();
  void dut_Xor_1Ux1U_1U_4_9();
  void drive_dout_m_req_m_prev_trig_req();
  void dut_Not_1U_1U_4_12();
};

#endif
