`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Nov 17 2020 22:52:56 EST (Nov 18 2020 03:52:56 UTC)

module dut_Add_4Sx2S_5S_1(in2, in1, out1);
  input [3:0] in2;
  input [1:0] in1;
  output [4:0] out1;
  wire [3:0] in2;
  wire [1:0] in1;
  wire [4:0] out1;
  wire add_35_2_n_0, add_35_2_n_1, add_35_2_n_2, add_35_2_n_3,
       add_35_2_n_4, add_35_2_n_5, add_35_2_n_6, add_35_2_n_7;
  wire add_35_2_n_8, add_35_2_n_9, add_35_2_n_11, add_35_2_n_13,
       add_35_2_n_14, add_35_2_n_15, add_35_2_n_16, add_35_2_n_17;
  wire add_35_2_n_19, add_35_2_n_21, add_35_2_n_22, add_35_2_n_25;
  MXI2X1 add_35_2_g75(.A (add_35_2_n_13), .B (add_35_2_n_14), .S0
       (add_35_2_n_25), .Y (out1[3]));
  OAI21X2 add_35_2_g76(.A0 (add_35_2_n_6), .A1 (add_35_2_n_21), .B0
       (add_35_2_n_9), .Y (add_35_2_n_25));
  NOR2BX1 add_35_2_g77(.AN (add_35_2_n_17), .B (add_35_2_n_22), .Y
       (out1[4]));
  NOR2X1 add_35_2_g79(.A (add_35_2_n_15), .B (add_35_2_n_21), .Y
       (add_35_2_n_22));
  NOR2X2 add_35_2_g80(.A (add_35_2_n_0), .B (add_35_2_n_19), .Y
       (add_35_2_n_21));
  NOR2X1 add_35_2_g82(.A (add_35_2_n_4), .B (add_35_2_n_8), .Y
       (add_35_2_n_19));
  AOI21X1 add_35_2_g84(.A0 (add_35_2_n_5), .A1 (add_35_2_n_1), .B0
       (add_35_2_n_7), .Y (add_35_2_n_17));
  NOR2X1 add_35_2_g85(.A (add_35_2_n_0), .B (add_35_2_n_8), .Y
       (add_35_2_n_16));
  NAND2BX1 add_35_2_g86(.AN (add_35_2_n_6), .B (add_35_2_n_5), .Y
       (add_35_2_n_15));
  INVXL add_35_2_g87(.A (add_35_2_n_13), .Y (add_35_2_n_14));
  NAND2BX1 add_35_2_g88(.AN (add_35_2_n_7), .B (add_35_2_n_5), .Y
       (add_35_2_n_13));
  NOR2X1 add_35_2_g90(.A (add_35_2_n_6), .B (add_35_2_n_1), .Y
       (add_35_2_n_11));
  MXI2XL add_35_2_g91(.A (add_35_2_n_3), .B (in2[0]), .S0 (in1[0]), .Y
       (out1[0]));
  INVX1 add_35_2_g92(.A (add_35_2_n_1), .Y (add_35_2_n_9));
  NOR2X2 add_35_2_g94(.A (in2[1]), .B (in1[1]), .Y (add_35_2_n_8));
  NOR2X1 add_35_2_g95(.A (in2[3]), .B (in1[1]), .Y (add_35_2_n_7));
  NOR2X1 add_35_2_g97(.A (in2[2]), .B (in1[1]), .Y (add_35_2_n_6));
  NAND2X1 add_35_2_g98(.A (in2[3]), .B (in1[1]), .Y (add_35_2_n_5));
  NAND2X4 add_35_2_g99(.A (in2[0]), .B (in1[0]), .Y (add_35_2_n_4));
  INVX1 add_35_2_g100(.A (in2[0]), .Y (add_35_2_n_3));
  CLKINVX2 add_35_2_g102(.A (in1[1]), .Y (add_35_2_n_2));
  NOR2BX2 add_35_2_g2(.AN (in2[2]), .B (add_35_2_n_2), .Y
       (add_35_2_n_1));
  NOR2BX2 add_35_2_g104(.AN (in2[1]), .B (add_35_2_n_2), .Y
       (add_35_2_n_0));
  XNOR2X1 add_35_2_g105(.A (add_35_2_n_11), .B (add_35_2_n_21), .Y
       (out1[2]));
  XNOR2X1 add_35_2_g106(.A (add_35_2_n_4), .B (add_35_2_n_16), .Y
       (out1[1]));
endmodule

