`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Nov 18 2020 11:30:40 EST (Nov 18 2020 16:30:40 UTC)

module dut_Add_32Ux17U_32U_4(in2, in1, out1);
  input [31:0] in2;
  input [16:0] in1;
  output [31:0] out1;
  wire [31:0] in2;
  wire [16:0] in1;
  wire [31:0] out1;
  wire add_35_2_n_0, add_35_2_n_1, add_35_2_n_2, add_35_2_n_3,
       add_35_2_n_4, add_35_2_n_5, add_35_2_n_6, add_35_2_n_7;
  wire add_35_2_n_8, add_35_2_n_9, add_35_2_n_10, add_35_2_n_11,
       add_35_2_n_12, add_35_2_n_13, add_35_2_n_14, add_35_2_n_15;
  wire add_35_2_n_16, add_35_2_n_17, add_35_2_n_18, add_35_2_n_19,
       add_35_2_n_20, add_35_2_n_21, add_35_2_n_22, add_35_2_n_23;
  wire add_35_2_n_24, add_35_2_n_25, add_35_2_n_26, add_35_2_n_27,
       add_35_2_n_28, add_35_2_n_29, add_35_2_n_30, add_35_2_n_31;
  wire add_35_2_n_32, add_35_2_n_33, add_35_2_n_34, add_35_2_n_35,
       add_35_2_n_36, add_35_2_n_37, add_35_2_n_38, add_35_2_n_39;
  wire add_35_2_n_40, add_35_2_n_41, add_35_2_n_42, add_35_2_n_43,
       add_35_2_n_44, add_35_2_n_45, add_35_2_n_46, add_35_2_n_47;
  wire add_35_2_n_48, add_35_2_n_49, add_35_2_n_50, add_35_2_n_51,
       add_35_2_n_52, add_35_2_n_53, add_35_2_n_54, add_35_2_n_55;
  wire add_35_2_n_56, add_35_2_n_57, add_35_2_n_58, add_35_2_n_59,
       add_35_2_n_60, add_35_2_n_61, add_35_2_n_62, add_35_2_n_63;
  wire add_35_2_n_64, add_35_2_n_65, add_35_2_n_66, add_35_2_n_67,
       add_35_2_n_69, add_35_2_n_70, add_35_2_n_71, add_35_2_n_73;
  wire add_35_2_n_74, add_35_2_n_76, add_35_2_n_77, add_35_2_n_78,
       add_35_2_n_80, add_35_2_n_81, add_35_2_n_83, add_35_2_n_84;
  wire add_35_2_n_85, add_35_2_n_88, add_35_2_n_89, add_35_2_n_90,
       add_35_2_n_93, add_35_2_n_94, add_35_2_n_95, add_35_2_n_96;
  wire add_35_2_n_97, add_35_2_n_101, add_35_2_n_102, add_35_2_n_103,
       add_35_2_n_105, add_35_2_n_106, add_35_2_n_110, add_35_2_n_111;
  wire add_35_2_n_112, add_35_2_n_113, add_35_2_n_115, add_35_2_n_118,
       add_35_2_n_121, add_35_2_n_122, add_35_2_n_124, add_35_2_n_125;
  wire add_35_2_n_129, add_35_2_n_132, add_35_2_n_134;
  XNOR2X1 add_35_2_g994(.A (in2[31]), .B (add_35_2_n_134), .Y
       (out1[31]));
  XNOR2X1 add_35_2_g995(.A (in2[29]), .B (add_35_2_n_129), .Y
       (out1[29]));
  XNOR2X1 add_35_2_g996(.A (in2[30]), .B (add_35_2_n_132), .Y
       (out1[30]));
  XNOR2X1 add_35_2_g997(.A (in2[27]), .B (add_35_2_n_125), .Y
       (out1[27]));
  NAND2BX1 add_35_2_g998(.AN (add_35_2_n_132), .B (in2[30]), .Y
       (add_35_2_n_134));
  XNOR2X1 add_35_2_g999(.A (in2[25]), .B (add_35_2_n_121), .Y
       (out1[25]));
  NAND3BXL add_35_2_g1000(.AN (add_35_2_n_124), .B (in2[28]), .C
       (in2[29]), .Y (add_35_2_n_132));
  XNOR2X1 add_35_2_g1001(.A (in2[28]), .B (add_35_2_n_124), .Y
       (out1[28]));
  XNOR2X1 add_35_2_g1002(.A (in2[23]), .B (add_35_2_n_118), .Y
       (out1[23]));
  NAND2BX1 add_35_2_g1003(.AN (add_35_2_n_124), .B (in2[28]), .Y
       (add_35_2_n_129));
  XNOR2X1 add_35_2_g1004(.A (in2[19]), .B (add_35_2_n_111), .Y
       (out1[19]));
  XNOR2X1 add_35_2_g1005(.A (in2[21]), .B (add_35_2_n_112), .Y
       (out1[21]));
  XOR2XL add_35_2_g1006(.A (in2[26]), .B (add_35_2_n_122), .Y
       (out1[26]));
  NAND2X1 add_35_2_g1007(.A (in2[26]), .B (add_35_2_n_122), .Y
       (add_35_2_n_125));
  NAND4XL add_35_2_g1008(.A (in2[27]), .B (in2[26]), .C
       (add_35_2_n_16), .D (add_35_2_n_115), .Y (add_35_2_n_124));
  XOR2XL add_35_2_g1009(.A (in2[24]), .B (add_35_2_n_115), .Y
       (out1[24]));
  AND2XL add_35_2_g1010(.A (add_35_2_n_16), .B (add_35_2_n_115), .Y
       (add_35_2_n_122));
  NAND2X1 add_35_2_g1011(.A (in2[24]), .B (add_35_2_n_115), .Y
       (add_35_2_n_121));
  XNOR2X1 add_35_2_g1012(.A (add_35_2_n_39), .B (add_35_2_n_110), .Y
       (out1[15]));
  XOR2XL add_35_2_g1013(.A (in2[22]), .B (add_35_2_n_113), .Y
       (out1[22]));
  NAND2X1 add_35_2_g1014(.A (in2[22]), .B (add_35_2_n_113), .Y
       (add_35_2_n_118));
  XNOR2X1 add_35_2_g1015(.A (in2[20]), .B (add_35_2_n_0), .Y
       (out1[20]));
  XNOR2X1 add_35_2_g1016(.A (in2[18]), .B (add_35_2_n_105), .Y
       (out1[18]));
  NOR4BBX1 add_35_2_g1017(.AN (in2[23]), .BN (in2[22]), .C
       (add_35_2_n_27), .D (add_35_2_n_0), .Y (add_35_2_n_115));
  XOR2XL add_35_2_g1018(.A (in2[17]), .B (add_35_2_n_106), .Y
       (out1[17]));
  NOR2X1 add_35_2_g1019(.A (add_35_2_n_27), .B (add_35_2_n_0), .Y
       (add_35_2_n_113));
  NAND2BX1 add_35_2_g1020(.AN (add_35_2_n_0), .B (in2[20]), .Y
       (add_35_2_n_112));
  NAND2BX1 add_35_2_g1021(.AN (add_35_2_n_105), .B (in2[18]), .Y
       (add_35_2_n_111));
  OAI21X1 add_35_2_g1022(.A0 (add_35_2_n_11), .A1 (add_35_2_n_103), .B0
       (add_35_2_n_19), .Y (add_35_2_n_110));
  XNOR2X1 add_35_2_g1023(.A (add_35_2_n_37), .B (add_35_2_n_103), .Y
       (out1[14]));
  XNOR2X1 add_35_2_g1024(.A (add_35_2_n_47), .B (add_35_2_n_102), .Y
       (out1[13]));
  XNOR2X1 add_35_2_g1025(.A (add_35_2_n_36), .B (add_35_2_n_101), .Y
       (out1[11]));
  OAI21X1 add_35_2_g1027(.A0 (add_35_2_n_24), .A1 (add_35_2_n_96), .B0
       (add_35_2_n_8), .Y (add_35_2_n_106));
  AOI21X1 add_35_2_g1029(.A0 (add_35_2_n_56), .A1 (add_35_2_n_97), .B0
       (add_35_2_n_43), .Y (add_35_2_n_105));
  XNOR2X1 add_35_2_g1030(.A (add_35_2_n_40), .B (add_35_2_n_97), .Y
       (out1[16]));
  AOI21X1 add_35_2_g1031(.A0 (add_35_2_n_58), .A1 (add_35_2_n_95), .B0
       (add_35_2_n_60), .Y (add_35_2_n_103));
  OAI2BB1X1 add_35_2_g1032(.A0N (add_35_2_n_5), .A1N (add_35_2_n_95),
       .B0 (add_35_2_n_12), .Y (add_35_2_n_102));
  OAI21X1 add_35_2_g1033(.A0 (add_35_2_n_20), .A1 (add_35_2_n_94), .B0
       (add_35_2_n_18), .Y (add_35_2_n_101));
  XNOR2X1 add_35_2_g1034(.A (add_35_2_n_38), .B (add_35_2_n_95), .Y
       (out1[12]));
  XNOR2X1 add_35_2_g1035(.A (add_35_2_n_41), .B (add_35_2_n_94), .Y
       (out1[10]));
  XNOR2X1 add_35_2_g1036(.A (add_35_2_n_42), .B (add_35_2_n_93), .Y
       (out1[9]));
  INVX1 add_35_2_g1037(.A (add_35_2_n_97), .Y (add_35_2_n_96));
  OAI31X1 add_35_2_g1038(.A0 (add_35_2_n_64), .A1 (add_35_2_n_66), .A2
       (add_35_2_n_89), .B0 (add_35_2_n_76), .Y (add_35_2_n_97));
  OAI211X1 add_35_2_g1039(.A0 (add_35_2_n_64), .A1 (add_35_2_n_89), .B0
       (add_35_2_n_61), .C0 (add_35_2_n_70), .Y (add_35_2_n_95));
  AOI21X1 add_35_2_g1040(.A0 (add_35_2_n_44), .A1 (add_35_2_n_88), .B0
       (add_35_2_n_62), .Y (add_35_2_n_94));
  OAI21X1 add_35_2_g1041(.A0 (add_35_2_n_14), .A1 (add_35_2_n_89), .B0
       (add_35_2_n_13), .Y (add_35_2_n_93));
  XNOR2X1 add_35_2_g1042(.A (add_35_2_n_35), .B (add_35_2_n_89), .Y
       (out1[8]));
  XNOR2X1 add_35_2_g1043(.A (add_35_2_n_49), .B (add_35_2_n_90), .Y
       (out1[7]));
  OAI21X1 add_35_2_g1044(.A0 (add_35_2_n_10), .A1 (add_35_2_n_83), .B0
       (add_35_2_n_3), .Y (add_35_2_n_90));
  INVX1 add_35_2_g1045(.A (add_35_2_n_88), .Y (add_35_2_n_89));
  OAI211X1 add_35_2_g1046(.A0 (add_35_2_n_3), .A1 (add_35_2_n_2), .B0
       (add_35_2_n_85), .C0 (add_35_2_n_69), .Y (add_35_2_n_88));
  XNOR2X1 add_35_2_g1047(.A (add_35_2_n_51), .B (add_35_2_n_83), .Y
       (out1[6]));
  XNOR2X1 add_35_2_g1048(.A (add_35_2_n_50), .B (add_35_2_n_84), .Y
       (out1[5]));
  AOI31X1 add_35_2_g1049(.A0 (add_35_2_n_55), .A1 (add_35_2_n_46), .A2
       (add_35_2_n_80), .B0 (add_35_2_n_34), .Y (add_35_2_n_85));
  OAI21X1 add_35_2_g1050(.A0 (add_35_2_n_4), .A1 (add_35_2_n_81), .B0
       (add_35_2_n_7), .Y (add_35_2_n_84));
  AOI21X1 add_35_2_g1051(.A0 (add_35_2_n_55), .A1 (add_35_2_n_80), .B0
       (add_35_2_n_59), .Y (add_35_2_n_83));
  XNOR2X1 add_35_2_g1052(.A (add_35_2_n_48), .B (add_35_2_n_81), .Y
       (out1[4]));
  INVX1 add_35_2_g1053(.A (add_35_2_n_80), .Y (add_35_2_n_81));
  OAI21X1 add_35_2_g1054(.A0 (add_35_2_n_17), .A1 (add_35_2_n_77), .B0
       (add_35_2_n_31), .Y (add_35_2_n_80));
  XNOR2X1 add_35_2_g1055(.A (add_35_2_n_53), .B (add_35_2_n_78), .Y
       (out1[3]));
  OAI2BB1X1 add_35_2_g1056(.A0N (add_35_2_n_9), .A1N (add_35_2_n_73),
       .B0 (add_35_2_n_23), .Y (add_35_2_n_78));
  AOI21X1 add_35_2_g1057(.A0 (add_35_2_n_9), .A1 (add_35_2_n_73), .B0
       (add_35_2_n_22), .Y (add_35_2_n_77));
  AOI211XL add_35_2_g1058(.A0 (add_35_2_n_45), .A1 (add_35_2_n_60), .B0
       (add_35_2_n_74), .C0 (add_35_2_n_54), .Y (add_35_2_n_76));
  XNOR2X1 add_35_2_g1059(.A (add_35_2_n_52), .B (add_35_2_n_73), .Y
       (out1[2]));
  OAI21XL add_35_2_g1060(.A0 (add_35_2_n_66), .A1 (add_35_2_n_71), .B0
       (add_35_2_n_32), .Y (add_35_2_n_74));
  ADDFX1 add_35_2_g1061(.A (add_35_2_n_67), .B (in1[1]), .CI (in2[1]),
       .CO (add_35_2_n_73), .S (out1[1]));
  AND2XL add_35_2_g1062(.A (add_35_2_n_61), .B (add_35_2_n_70), .Y
       (add_35_2_n_71));
  NAND2X1 add_35_2_g1063(.A (add_35_2_n_57), .B (add_35_2_n_62), .Y
       (add_35_2_n_70));
  NAND2X1 add_35_2_g1064(.A (add_35_2_n_46), .B (add_35_2_n_59), .Y
       (add_35_2_n_69));
  ADDHX1 add_35_2_g1065(.A (in2[0]), .B (in1[0]), .CO (add_35_2_n_67),
       .S (out1[0]));
  NAND2X1 add_35_2_g1066(.A (add_35_2_n_45), .B (add_35_2_n_58), .Y
       (add_35_2_n_66));
  NOR2BX1 add_35_2_g1067(.AN (add_35_2_n_56), .B (add_35_2_n_15), .Y
       (add_35_2_n_65));
  NAND2X1 add_35_2_g1068(.A (add_35_2_n_57), .B (add_35_2_n_44), .Y
       (add_35_2_n_64));
  NOR2BX1 add_35_2_g1069(.AN (add_35_2_n_43), .B (add_35_2_n_15), .Y
       (add_35_2_n_63));
  OAI21X1 add_35_2_g1070(.A0 (add_35_2_n_13), .A1 (add_35_2_n_26), .B0
       (add_35_2_n_30), .Y (add_35_2_n_62));
  OA21X1 add_35_2_g1071(.A0 (add_35_2_n_18), .A1 (add_35_2_n_25), .B0
       (add_35_2_n_28), .Y (add_35_2_n_61));
  OAI21X1 add_35_2_g1072(.A0 (add_35_2_n_12), .A1 (add_35_2_n_21), .B0
       (add_35_2_n_29), .Y (add_35_2_n_60));
  OAI21X1 add_35_2_g1073(.A0 (add_35_2_n_7), .A1 (add_35_2_n_6), .B0
       (add_35_2_n_33), .Y (add_35_2_n_59));
  NOR2X1 add_35_2_g1074(.A (add_35_2_n_19), .B (add_35_2_n_1), .Y
       (add_35_2_n_54));
  NOR2BX1 add_35_2_g1075(.AN (add_35_2_n_5), .B (add_35_2_n_21), .Y
       (add_35_2_n_58));
  NOR2X1 add_35_2_g1076(.A (add_35_2_n_25), .B (add_35_2_n_20), .Y
       (add_35_2_n_57));
  NAND2BX1 add_35_2_g1077(.AN (add_35_2_n_17), .B (add_35_2_n_31), .Y
       (add_35_2_n_53));
  NAND2X1 add_35_2_g1078(.A (add_35_2_n_23), .B (add_35_2_n_9), .Y
       (add_35_2_n_52));
  NOR2BX1 add_35_2_g1079(.AN (in2[17]), .B (add_35_2_n_24), .Y
       (add_35_2_n_56));
  NOR2BX1 add_35_2_g1080(.AN (add_35_2_n_3), .B (add_35_2_n_10), .Y
       (add_35_2_n_51));
  NAND2BX1 add_35_2_g1081(.AN (add_35_2_n_6), .B (add_35_2_n_33), .Y
       (add_35_2_n_50));
  OR2XL add_35_2_g1082(.A (add_35_2_n_34), .B (add_35_2_n_2), .Y
       (add_35_2_n_49));
  NOR2BX1 add_35_2_g1083(.AN (add_35_2_n_7), .B (add_35_2_n_4), .Y
       (add_35_2_n_48));
  NAND2BX1 add_35_2_g1084(.AN (add_35_2_n_21), .B (add_35_2_n_29), .Y
       (add_35_2_n_47));
  NOR2X1 add_35_2_g1085(.A (add_35_2_n_6), .B (add_35_2_n_4), .Y
       (add_35_2_n_55));
  NOR2X1 add_35_2_g1086(.A (add_35_2_n_2), .B (add_35_2_n_10), .Y
       (add_35_2_n_46));
  NAND2BX1 add_35_2_g1087(.AN (add_35_2_n_26), .B (add_35_2_n_30), .Y
       (add_35_2_n_42));
  NOR2BX1 add_35_2_g1088(.AN (add_35_2_n_18), .B (add_35_2_n_20), .Y
       (add_35_2_n_41));
  NOR2X1 add_35_2_g1089(.A (add_35_2_n_1), .B (add_35_2_n_11), .Y
       (add_35_2_n_45));
  NAND2BX1 add_35_2_g1090(.AN (add_35_2_n_24), .B (add_35_2_n_8), .Y
       (add_35_2_n_40));
  NAND2BX1 add_35_2_g1091(.AN (add_35_2_n_1), .B (add_35_2_n_32), .Y
       (add_35_2_n_39));
  NOR2X1 add_35_2_g1092(.A (add_35_2_n_26), .B (add_35_2_n_14), .Y
       (add_35_2_n_44));
  NAND2X1 add_35_2_g1093(.A (add_35_2_n_12), .B (add_35_2_n_5), .Y
       (add_35_2_n_38));
  NOR2BX1 add_35_2_g1094(.AN (add_35_2_n_19), .B (add_35_2_n_11), .Y
       (add_35_2_n_37));
  NAND2BX1 add_35_2_g1095(.AN (add_35_2_n_25), .B (add_35_2_n_28), .Y
       (add_35_2_n_36));
  NOR2BX1 add_35_2_g1096(.AN (add_35_2_n_13), .B (add_35_2_n_14), .Y
       (add_35_2_n_35));
  NOR2BX1 add_35_2_g1097(.AN (in2[17]), .B (add_35_2_n_8), .Y
       (add_35_2_n_43));
  INVX1 add_35_2_g1098(.A (add_35_2_n_23), .Y (add_35_2_n_22));
  AND2XL add_35_2_g1099(.A (in2[7]), .B (in1[7]), .Y (add_35_2_n_34));
  NAND2X1 add_35_2_g1100(.A (in2[5]), .B (in1[5]), .Y (add_35_2_n_33));
  NAND2X1 add_35_2_g1101(.A (in2[15]), .B (in1[15]), .Y
       (add_35_2_n_32));
  NAND2X1 add_35_2_g1102(.A (in2[3]), .B (in1[3]), .Y (add_35_2_n_31));
  NAND2X1 add_35_2_g1103(.A (in2[9]), .B (in1[9]), .Y (add_35_2_n_30));
  NAND2X1 add_35_2_g1104(.A (in2[13]), .B (in1[13]), .Y
       (add_35_2_n_29));
  NAND2X1 add_35_2_g1105(.A (in2[11]), .B (in1[11]), .Y
       (add_35_2_n_28));
  NAND2X1 add_35_2_g1106(.A (in2[21]), .B (in2[20]), .Y
       (add_35_2_n_27));
  NOR2X1 add_35_2_g1107(.A (in2[9]), .B (in1[9]), .Y (add_35_2_n_26));
  NOR2X1 add_35_2_g1108(.A (in2[11]), .B (in1[11]), .Y (add_35_2_n_25));
  NOR2X1 add_35_2_g1109(.A (in2[16]), .B (in1[16]), .Y (add_35_2_n_24));
  NAND2X1 add_35_2_g1110(.A (in2[2]), .B (in1[2]), .Y (add_35_2_n_23));
  NOR2X1 add_35_2_g1111(.A (in2[13]), .B (in1[13]), .Y (add_35_2_n_21));
  NOR2X1 add_35_2_g1112(.A (in2[10]), .B (in1[10]), .Y (add_35_2_n_20));
  NAND2X1 add_35_2_g1113(.A (in2[14]), .B (in1[14]), .Y
       (add_35_2_n_19));
  NAND2X1 add_35_2_g1114(.A (in2[10]), .B (in1[10]), .Y
       (add_35_2_n_18));
  NOR2X1 add_35_2_g1115(.A (in2[3]), .B (in1[3]), .Y (add_35_2_n_17));
  AND2XL add_35_2_g1116(.A (in2[25]), .B (in2[24]), .Y (add_35_2_n_16));
  NAND2X1 add_35_2_g1117(.A (in2[19]), .B (in2[18]), .Y
       (add_35_2_n_15));
  NOR2X1 add_35_2_g1118(.A (in2[8]), .B (in1[8]), .Y (add_35_2_n_14));
  NAND2X1 add_35_2_g1119(.A (in2[8]), .B (in1[8]), .Y (add_35_2_n_13));
  NAND2X1 add_35_2_g1120(.A (in2[12]), .B (in1[12]), .Y
       (add_35_2_n_12));
  NOR2X1 add_35_2_g1121(.A (in2[14]), .B (in1[14]), .Y (add_35_2_n_11));
  NOR2X1 add_35_2_g1122(.A (in2[6]), .B (in1[6]), .Y (add_35_2_n_10));
  OR2X1 add_35_2_g1123(.A (in2[2]), .B (in1[2]), .Y (add_35_2_n_9));
  NAND2X1 add_35_2_g1124(.A (in2[16]), .B (in1[16]), .Y (add_35_2_n_8));
  NAND2X1 add_35_2_g1125(.A (in2[4]), .B (in1[4]), .Y (add_35_2_n_7));
  NOR2X1 add_35_2_g1126(.A (in2[5]), .B (in1[5]), .Y (add_35_2_n_6));
  OR2X1 add_35_2_g1127(.A (in2[12]), .B (in1[12]), .Y (add_35_2_n_5));
  NOR2X1 add_35_2_g1128(.A (in2[4]), .B (in1[4]), .Y (add_35_2_n_4));
  NAND2X1 add_35_2_g1129(.A (in2[6]), .B (in1[6]), .Y (add_35_2_n_3));
  NOR2X1 add_35_2_g1130(.A (in2[7]), .B (in1[7]), .Y (add_35_2_n_2));
  NOR2X1 add_35_2_g1131(.A (in2[15]), .B (in1[15]), .Y (add_35_2_n_1));
  AOI21X1 add_35_2_g1132(.A0 (add_35_2_n_65), .A1 (add_35_2_n_97), .B0
       (add_35_2_n_63), .Y (add_35_2_n_0));
endmodule


