`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Nov 18 2020 11:31:10 EST (Nov 18 2020 16:31:10 UTC)

module dut_Not_1U_1U_1(in1, out1);
  input in1;
  output out1;
  wire in1;
  wire out1;
  CLKINVX12 g2(.A (in1), .Y (out1));
endmodule


