`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Nov 18 2020 11:32:32 EST (Nov 18 2020 16:32:32 UTC)

module dut_Add_9Ux8U_10U_1(in2, in1, out1);
  input [8:0] in2;
  input [7:0] in1;
  output [9:0] out1;
  wire [8:0] in2;
  wire [7:0] in1;
  wire [9:0] out1;
  wire add_35_2_n_1, add_35_2_n_5, add_35_2_n_7, add_35_2_n_8,
       add_35_2_n_9, add_35_2_n_10, add_35_2_n_11, add_35_2_n_12;
  wire add_35_2_n_13, add_35_2_n_14, add_35_2_n_15, add_35_2_n_16,
       add_35_2_n_17, add_35_2_n_18, add_35_2_n_19, add_35_2_n_20;
  wire add_35_2_n_21, add_35_2_n_22, add_35_2_n_23, add_35_2_n_24,
       add_35_2_n_25, add_35_2_n_26, add_35_2_n_27, add_35_2_n_28;
  wire add_35_2_n_29, add_35_2_n_30, add_35_2_n_31, add_35_2_n_32,
       add_35_2_n_33, add_35_2_n_34, add_35_2_n_35, add_35_2_n_36;
  wire add_35_2_n_37, add_35_2_n_38, add_35_2_n_39, add_35_2_n_40,
       add_35_2_n_41, add_35_2_n_42, add_35_2_n_43, add_35_2_n_44;
  wire add_35_2_n_45, add_35_2_n_46, add_35_2_n_47, add_35_2_n_48,
       add_35_2_n_49, add_35_2_n_50, add_35_2_n_51, add_35_2_n_52;
  wire add_35_2_n_53, add_35_2_n_54, add_35_2_n_55, add_35_2_n_56,
       add_35_2_n_79, add_35_2_n_80, add_35_2_n_81, add_35_2_n_83;
  wire add_35_2_n_84, add_35_2_n_85, add_35_2_n_88;
  MXI2X1 add_35_2_g189(.A (in2[8]), .B (add_35_2_n_7), .S0
       (add_35_2_n_56), .Y (out1[8]));
  MXI2XL add_35_2_g190(.A (add_35_2_n_36), .B (add_35_2_n_35), .S0
       (add_35_2_n_5), .Y (out1[6]));
  MXI2XL add_35_2_g191(.A (add_35_2_n_32), .B (add_35_2_n_33), .S0
       (add_35_2_n_55), .Y (out1[5]));
  MXI2XL add_35_2_g192(.A (add_35_2_n_27), .B (add_35_2_n_28), .S0
       (add_35_2_n_54), .Y (out1[7]));
  NOR2X1 add_35_2_g193(.A (add_35_2_n_7), .B (add_35_2_n_56), .Y
       (out1[9]));
  NOR2X1 add_35_2_g194(.A (add_35_2_n_44), .B (add_35_2_n_51), .Y
       (add_35_2_n_56));
  NOR2BX1 add_35_2_g196(.AN (add_35_2_n_21), .B (add_35_2_n_52), .Y
       (add_35_2_n_55));
  NOR2X1 add_35_2_g199(.A (add_35_2_n_45), .B (add_35_2_n_50), .Y
       (add_35_2_n_54));
  NOR2X1 add_35_2_g200(.A (add_35_2_n_26), .B (add_35_2_n_48), .Y
       (add_35_2_n_53));
  NOR2X1 add_35_2_g201(.A (add_35_2_n_12), .B (add_35_2_n_48), .Y
       (add_35_2_n_52));
  NOR2X1 add_35_2_g202(.A (add_35_2_n_41), .B (add_35_2_n_48), .Y
       (add_35_2_n_51));
  NOR2X1 add_35_2_g203(.A (add_35_2_n_40), .B (add_35_2_n_48), .Y
       (add_35_2_n_50));
  NOR2BX1 add_35_2_g204(.AN (add_35_2_n_11), .B (add_35_2_n_47), .Y
       (add_35_2_n_49));
  NOR2X2 add_35_2_g206(.A (add_35_2_n_37), .B (add_35_2_n_46), .Y
       (add_35_2_n_48));
  NOR2X1 add_35_2_g207(.A (add_35_2_n_20), .B (add_35_2_n_80), .Y
       (add_35_2_n_47));
  NOR2X2 add_35_2_g208(.A (add_35_2_n_30), .B (add_35_2_n_43), .Y
       (add_35_2_n_46));
  OAI21X1 add_35_2_g209(.A0 (add_35_2_n_84), .A1 (add_35_2_n_39), .B0
       (add_35_2_n_14), .Y (add_35_2_n_45));
  OAI21X1 add_35_2_g210(.A0 (add_35_2_n_34), .A1 (add_35_2_n_39), .B0
       (add_35_2_n_38), .Y (add_35_2_n_44));
  NOR2X2 add_35_2_g211(.A (add_35_2_n_24), .B (add_35_2_n_42), .Y
       (add_35_2_n_43));
  NOR2X2 add_35_2_g213(.A (add_35_2_n_10), .B (add_35_2_n_16), .Y
       (add_35_2_n_42));
  OR2XL add_35_2_g215(.A (add_35_2_n_34), .B (add_35_2_n_26), .Y
       (add_35_2_n_41));
  OR2XL add_35_2_g216(.A (add_35_2_n_18), .B (add_35_2_n_26), .Y
       (add_35_2_n_40));
  AOI2BB1X1 add_35_2_g218(.A0N (add_35_2_n_21), .A1N (add_35_2_n_13),
       .B0 (add_35_2_n_23), .Y (add_35_2_n_39));
  OA21X1 add_35_2_g219(.A0 (add_35_2_n_14), .A1 (add_35_2_n_15), .B0
       (add_35_2_n_17), .Y (add_35_2_n_38));
  OAI21X1 add_35_2_g220(.A0 (add_35_2_n_11), .A1 (add_35_2_n_19), .B0
       (add_35_2_n_22), .Y (add_35_2_n_37));
  INVX1 add_35_2_g221(.A (add_35_2_n_35), .Y (add_35_2_n_36));
  INVX1 add_35_2_g222(.A (add_35_2_n_32), .Y (add_35_2_n_33));
  OR2XL add_35_2_g224(.A (add_35_2_n_19), .B (add_35_2_n_20), .Y
       (add_35_2_n_30));
  NAND2BX1 add_35_2_g225(.AN (add_35_2_n_83), .B (add_35_2_n_14), .Y
       (add_35_2_n_35));
  OR2XL add_35_2_g226(.A (add_35_2_n_15), .B (add_35_2_n_18), .Y
       (add_35_2_n_34));
  NOR2X1 add_35_2_g227(.A (add_35_2_n_23), .B (add_35_2_n_13), .Y
       (add_35_2_n_32));
  NAND2BX1 add_35_2_g228(.AN (add_35_2_n_12), .B (add_35_2_n_21), .Y
       (add_35_2_n_31));
  INVX1 add_35_2_g231(.A (add_35_2_n_27), .Y (add_35_2_n_28));
  NOR2X1 add_35_2_g234(.A (add_35_2_n_24), .B (add_35_2_n_16), .Y
       (add_35_2_n_25));
  NOR2BX1 add_35_2_g235(.AN (add_35_2_n_22), .B (add_35_2_n_88), .Y
       (add_35_2_n_29));
  NOR2BX1 add_35_2_g236(.AN (add_35_2_n_17), .B (add_35_2_n_15), .Y
       (add_35_2_n_27));
  OR2XL add_35_2_g237(.A (add_35_2_n_13), .B (add_35_2_n_12), .Y
       (add_35_2_n_26));
  NOR2X2 add_35_2_g239(.A (add_35_2_n_8), .B (add_35_2_n_9), .Y
       (add_35_2_n_24));
  AND2X1 add_35_2_g240(.A (in2[5]), .B (in1[5]), .Y (add_35_2_n_23));
  NAND2X1 add_35_2_g241(.A (in2[3]), .B (in1[3]), .Y (add_35_2_n_22));
  NAND2X1 add_35_2_g242(.A (in2[4]), .B (in1[4]), .Y (add_35_2_n_21));
  NOR2X2 add_35_2_g243(.A (in2[2]), .B (in1[2]), .Y (add_35_2_n_20));
  NOR2X8 add_35_2_g244(.A (in2[3]), .B (in1[3]), .Y (add_35_2_n_19));
  NOR2X1 add_35_2_g245(.A (in2[6]), .B (in1[6]), .Y (add_35_2_n_18));
  NAND2X1 add_35_2_g246(.A (in2[7]), .B (in1[7]), .Y (add_35_2_n_17));
  NOR2X8 add_35_2_g247(.A (in2[1]), .B (in1[1]), .Y (add_35_2_n_16));
  NOR2X2 add_35_2_g248(.A (in2[7]), .B (in1[7]), .Y (add_35_2_n_15));
  NAND2X1 add_35_2_g249(.A (in2[6]), .B (in1[6]), .Y (add_35_2_n_14));
  NOR2X2 add_35_2_g250(.A (in2[5]), .B (in1[5]), .Y (add_35_2_n_13));
  NOR2X1 add_35_2_g251(.A (in2[4]), .B (in1[4]), .Y (add_35_2_n_12));
  NAND2X1 add_35_2_g252(.A (in2[2]), .B (in1[2]), .Y (add_35_2_n_11));
  NAND2X6 add_35_2_g253(.A (in2[0]), .B (in1[0]), .Y (add_35_2_n_10));
  CLKINVX2 add_35_2_g254(.A (in1[1]), .Y (add_35_2_n_9));
  CLKINVX2 add_35_2_g255(.A (in2[1]), .Y (add_35_2_n_8));
  INVX1 add_35_2_g257(.A (in2[8]), .Y (add_35_2_n_7));
  XNOR2X1 add_35_2_g2(.A (add_35_2_n_10), .B (add_35_2_n_25), .Y
       (out1[1]));
  NOR2BX1 add_35_2_g258(.AN (add_35_2_n_39), .B (add_35_2_n_53), .Y
       (add_35_2_n_5));
  CLKXOR2X1 add_35_2_g259(.A (add_35_2_n_31), .B (add_35_2_n_48), .Y
       (out1[4]));
  CLKXOR2X1 add_35_2_g260(.A (add_35_2_n_1), .B (add_35_2_n_79), .Y
       (out1[2]));
  XNOR2X1 add_35_2_g261(.A (add_35_2_n_29), .B (add_35_2_n_49), .Y
       (out1[3]));
  NAND2BX1 add_35_2_g262(.AN (add_35_2_n_20), .B (add_35_2_n_11), .Y
       (add_35_2_n_1));
  XOR2XL add_35_2_g263(.A (in2[0]), .B (in1[0]), .Y (out1[0]));
  INVXL add_35_2_fopt(.A (add_35_2_n_81), .Y (add_35_2_n_79));
  INVXL add_35_2_fopt264(.A (add_35_2_n_81), .Y (add_35_2_n_80));
  INVXL add_35_2_fopt265(.A (add_35_2_n_43), .Y (add_35_2_n_81));
  INVXL add_35_2_fopt266(.A (add_35_2_n_85), .Y (add_35_2_n_83));
  INVXL add_35_2_fopt267(.A (add_35_2_n_85), .Y (add_35_2_n_84));
  INVXL add_35_2_fopt268(.A (add_35_2_n_18), .Y (add_35_2_n_85));
  BUFX2 add_35_2_fopt269(.A (add_35_2_n_19), .Y (add_35_2_n_88));
endmodule


