`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Nov 20 2020 12:05:30 EST (Nov 20 2020 17:05:30 UTC)

module dut_LessThan_4Ux4U_1U_4(in2, in1, out1);
  input [3:0] in2, in1;
  output out1;
  wire [3:0] in2, in1;
  wire out1;
  wire gt_33_21_n_0, gt_33_21_n_1, gt_33_21_n_2, gt_33_21_n_3,
       gt_33_21_n_4, gt_33_21_n_5, gt_33_21_n_6, gt_33_21_n_7;
  AOI221X1 gt_33_21_g102(.A0 (in2[2]), .A1 (gt_33_21_n_5), .B0
       (in2[3]), .B1 (gt_33_21_n_1), .C0 (gt_33_21_n_7), .Y (out1));
  AOI221X1 gt_33_21_g103(.A0 (in1[2]), .A1 (gt_33_21_n_0), .B0
       (gt_33_21_n_4), .B1 (gt_33_21_n_6), .C0 (gt_33_21_n_2), .Y
       (gt_33_21_n_7));
  OAI2BB1X1 gt_33_21_g104(.A0N (in1[1]), .A1N (gt_33_21_n_3), .B0
       (in2[1]), .Y (gt_33_21_n_6));
  NOR2X1 gt_33_21_g105(.A (in1[2]), .B (gt_33_21_n_2), .Y
       (gt_33_21_n_5));
  OR2XL gt_33_21_g106(.A (in1[1]), .B (gt_33_21_n_3), .Y
       (gt_33_21_n_4));
  NOR2BX1 gt_33_21_g107(.AN (in1[0]), .B (in2[0]), .Y (gt_33_21_n_3));
  NOR2X1 gt_33_21_g108(.A (gt_33_21_n_1), .B (in2[3]), .Y
       (gt_33_21_n_2));
  INVX1 gt_33_21_g109(.A (in1[3]), .Y (gt_33_21_n_1));
  INVX1 gt_33_21_g110(.A (in2[2]), .Y (gt_33_21_n_0));
endmodule

