
// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Nov 17 2020 14:52:58 EST (Nov 17 2020 19:52:58 UTC)

module test_mux_1_2(data0, data1, ctrl, out);
  input [0:0] data0, data1;
  input [1:0] ctrl;
  output [0:0] out;
  wire [0:0] data0, data1;
  wire [1:0] ctrl;
  wire [0:0] out;
  AO22XL g18(.A0 (data0), .A1 (ctrl[0]), .B0 (data1), .B1 (ctrl[1]), .Y
       (out));
endmodule

