`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Nov 17 2020 22:53:40 EST (Nov 18 2020 03:53:40 UTC)

module dut_Add_10Ux8U_11U_4(in2, in1, out1);
  input [9:0] in2;
  input [7:0] in1;
  output [10:0] out1;
  wire [9:0] in2;
  wire [7:0] in1;
  wire [10:0] out1;
  wire add_35_2_n_0, add_35_2_n_1, add_35_2_n_2, add_35_2_n_3,
       add_35_2_n_4, add_35_2_n_5, add_35_2_n_6, add_35_2_n_7;
  wire add_35_2_n_8, add_35_2_n_9, add_35_2_n_10, add_35_2_n_11,
       add_35_2_n_12, add_35_2_n_13, add_35_2_n_14, add_35_2_n_15;
  wire add_35_2_n_17, add_35_2_n_18, add_35_2_n_20, add_35_2_n_23,
       add_35_2_n_24, add_35_2_n_26, add_35_2_n_27, add_35_2_n_30;
  wire add_35_2_n_31, add_35_2_n_33;
  ADDHX1 add_35_2_g304(.A (in2[9]), .B (add_35_2_n_33), .CO (out1[10]),
       .S (out1[9]));
  ADDHX1 add_35_2_g305(.A (in2[8]), .B (add_35_2_n_30), .CO
       (add_35_2_n_33), .S (out1[8]));
  XNOR2X1 add_35_2_g306(.A (add_35_2_n_9), .B (add_35_2_n_31), .Y
       (out1[7]));
  OAI21X1 add_35_2_g307(.A0 (add_35_2_n_5), .A1 (add_35_2_n_27), .B0
       (add_35_2_n_6), .Y (add_35_2_n_31));
  OAI211X1 add_35_2_g308(.A0 (add_35_2_n_8), .A1 (add_35_2_n_24), .B0
       (add_35_2_n_17), .C0 (add_35_2_n_2), .Y (add_35_2_n_30));
  XNOR2X1 add_35_2_g309(.A (add_35_2_n_11), .B (add_35_2_n_27), .Y
       (out1[6]));
  XNOR2X1 add_35_2_g310(.A (add_35_2_n_10), .B (add_35_2_n_26), .Y
       (out1[5]));
  NOR2BX1 add_35_2_g311(.AN (add_35_2_n_24), .B (add_35_2_n_13), .Y
       (add_35_2_n_27));
  OAI2BB1X1 add_35_2_g312(.A0N (add_35_2_n_0), .A1N (add_35_2_n_23),
       .B0 (add_35_2_n_7), .Y (add_35_2_n_26));
  XNOR2X1 add_35_2_g313(.A (add_35_2_n_12), .B (add_35_2_n_23), .Y
       (out1[4]));
  NAND3BXL add_35_2_g314(.AN (add_35_2_n_1), .B (add_35_2_n_23), .C
       (add_35_2_n_0), .Y (add_35_2_n_24));
  ADDFX1 add_35_2_g315(.A (add_35_2_n_20), .B (in1[3]), .CI (in2[3]),
       .CO (add_35_2_n_23), .S (out1[3]));
  ADDFX1 add_35_2_g316(.A (add_35_2_n_18), .B (in1[2]), .CI (in2[2]),
       .CO (add_35_2_n_20), .S (out1[2]));
  ADDFX1 add_35_2_g317(.A (add_35_2_n_15), .B (in1[1]), .CI (in2[1]),
       .CO (add_35_2_n_18), .S (out1[1]));
  OA22X1 add_35_2_g318(.A0 (add_35_2_n_8), .A1 (add_35_2_n_14), .B0
       (add_35_2_n_6), .B1 (add_35_2_n_3), .Y (add_35_2_n_17));
  ADDHX1 add_35_2_g319(.A (in2[0]), .B (in1[0]), .CO (add_35_2_n_15),
       .S (out1[0]));
  INVXL add_35_2_g320(.A (add_35_2_n_13), .Y (add_35_2_n_14));
  OAI21X1 add_35_2_g321(.A0 (add_35_2_n_7), .A1 (add_35_2_n_1), .B0
       (add_35_2_n_4), .Y (add_35_2_n_13));
  NAND2X1 add_35_2_g322(.A (add_35_2_n_7), .B (add_35_2_n_0), .Y
       (add_35_2_n_12));
  NOR2BX1 add_35_2_g323(.AN (add_35_2_n_6), .B (add_35_2_n_5), .Y
       (add_35_2_n_11));
  NAND2BX1 add_35_2_g324(.AN (add_35_2_n_1), .B (add_35_2_n_4), .Y
       (add_35_2_n_10));
  NAND2BX1 add_35_2_g325(.AN (add_35_2_n_3), .B (add_35_2_n_2), .Y
       (add_35_2_n_9));
  OR2XL add_35_2_g326(.A (add_35_2_n_3), .B (add_35_2_n_5), .Y
       (add_35_2_n_8));
  NAND2X1 add_35_2_g327(.A (in2[4]), .B (in1[4]), .Y (add_35_2_n_7));
  NAND2X1 add_35_2_g328(.A (in2[6]), .B (in1[6]), .Y (add_35_2_n_6));
  NOR2X1 add_35_2_g329(.A (in2[6]), .B (in1[6]), .Y (add_35_2_n_5));
  NAND2X1 add_35_2_g330(.A (in2[5]), .B (in1[5]), .Y (add_35_2_n_4));
  NOR2X1 add_35_2_g331(.A (in2[7]), .B (in1[7]), .Y (add_35_2_n_3));
  NAND2X1 add_35_2_g332(.A (in2[7]), .B (in1[7]), .Y (add_35_2_n_2));
  NOR2X1 add_35_2_g333(.A (in2[5]), .B (in1[5]), .Y (add_35_2_n_1));
  OR2X1 add_35_2_g334(.A (in2[4]), .B (in1[4]), .Y (add_35_2_n_0));
endmodule

