// Generated by stratus_hls 17.20-p100  (88533.190925)
// Thu Nov 19 00:05:12 2020
// from dut.cc
#ifndef CYNTH_PART_dut_dut_Div_64Ux2U_32U_4_h
#define CYNTH_PART_dut_dut_Div_64Ux2U_32U_4_h

#include "systemc.h"
/* Include declarations of instantiated parts. */


/* Declaration of the synthesized module. */
struct dut_Div_64Ux2U_32U_4 : public sc_module {
  sc_in<sc_uint<64> > in2;
  sc_in<sc_uint<2> > in1;
  sc_out<sc_uint<32> > out1;
  sc_in<bool > clk;
  sc_in<sc_uint<1> > stall;
  dut_Div_64Ux2U_32U_4( sc_module_name name );
  SC_HAS_PROCESS(dut_Div_64Ux2U_32U_4);
  sc_uint<32> out1_0;
  void dut_Div_64Ux2U_32U_4_thread_1();
};

#endif
