`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Nov 17 2020 22:53:43 EST (Nov 18 2020 03:53:43 UTC)

module dut_Add_10Ux8U_11U_1(in2, in1, out1);
  input [9:0] in2;
  input [7:0] in1;
  output [10:0] out1;
  wire [9:0] in2;
  wire [7:0] in1;
  wire [10:0] out1;
  wire add_35_2_n_1, add_35_2_n_2, add_35_2_n_3, add_35_2_n_10,
       add_35_2_n_12, add_35_2_n_13, add_35_2_n_14, add_35_2_n_15;
  wire add_35_2_n_16, add_35_2_n_17, add_35_2_n_18, add_35_2_n_19,
       add_35_2_n_20, add_35_2_n_21, add_35_2_n_22, add_35_2_n_23;
  wire add_35_2_n_24, add_35_2_n_25, add_35_2_n_26, add_35_2_n_27,
       add_35_2_n_28, add_35_2_n_29, add_35_2_n_30, add_35_2_n_31;
  wire add_35_2_n_32, add_35_2_n_33, add_35_2_n_34, add_35_2_n_35,
       add_35_2_n_36, add_35_2_n_37, add_35_2_n_38, add_35_2_n_39;
  wire add_35_2_n_40, add_35_2_n_41, add_35_2_n_42, add_35_2_n_43,
       add_35_2_n_44, add_35_2_n_45, add_35_2_n_46, add_35_2_n_47;
  wire add_35_2_n_48, add_35_2_n_49, add_35_2_n_50, add_35_2_n_51,
       add_35_2_n_52, add_35_2_n_53, add_35_2_n_54, add_35_2_n_55;
  wire add_35_2_n_56, add_35_2_n_57, add_35_2_n_58, add_35_2_n_59,
       add_35_2_n_60, add_35_2_n_61, add_35_2_n_62, add_35_2_n_64;
  wire add_35_2_n_85, add_35_2_n_87, add_35_2_n_88, add_35_2_n_89,
       add_35_2_n_91, add_35_2_n_92, add_35_2_n_93, add_35_2_n_95;
  MXI2X1 add_35_2_g207(.A (add_35_2_n_13), .B (in2[9]), .S0
       (add_35_2_n_64), .Y (out1[9]));
  MXI2XL add_35_2_g208(.A (in2[8]), .B (add_35_2_n_12), .S0
       (add_35_2_n_62), .Y (out1[8]));
  NOR2X2 add_35_2_g212(.A (add_35_2_n_12), .B (add_35_2_n_62), .Y
       (add_35_2_n_64));
  NOR2X1 add_35_2_g213(.A (add_35_2_n_23), .B (add_35_2_n_85), .Y
       (out1[10]));
  NOR2X2 add_35_2_g214(.A (add_35_2_n_51), .B (add_35_2_n_57), .Y
       (add_35_2_n_62));
  NOR2BX1 add_35_2_g216(.AN (add_35_2_n_18), .B (add_35_2_n_58), .Y
       (add_35_2_n_61));
  NOR2X1 add_35_2_g219(.A (add_35_2_n_52), .B (add_35_2_n_56), .Y
       (add_35_2_n_60));
  NOR2X1 add_35_2_g220(.A (add_35_2_n_33), .B (add_35_2_n_54), .Y
       (add_35_2_n_59));
  NOR2X1 add_35_2_g221(.A (add_35_2_n_24), .B (add_35_2_n_54), .Y
       (add_35_2_n_58));
  NOR2X2 add_35_2_g222(.A (add_35_2_n_47), .B (add_35_2_n_54), .Y
       (add_35_2_n_57));
  NOR2X1 add_35_2_g223(.A (add_35_2_n_48), .B (add_35_2_n_54), .Y
       (add_35_2_n_56));
  NOR2BX1 add_35_2_g224(.AN (add_35_2_n_92), .B (add_35_2_n_3), .Y
       (add_35_2_n_55));
  NOR2X4 add_35_2_g226(.A (add_35_2_n_46), .B (add_35_2_n_53), .Y
       (add_35_2_n_54));
  NOR2X4 add_35_2_g228(.A (add_35_2_n_38), .B (add_35_2_n_50), .Y
       (add_35_2_n_53));
  OAI21X1 add_35_2_g229(.A0 (add_35_2_n_16), .A1 (add_35_2_n_45), .B0
       (add_35_2_n_21), .Y (add_35_2_n_52));
  OAI21X2 add_35_2_g230(.A0 (add_35_2_n_40), .A1 (add_35_2_n_45), .B0
       (add_35_2_n_44), .Y (add_35_2_n_51));
  NOR2X4 add_35_2_g231(.A (add_35_2_n_1), .B (add_35_2_n_49), .Y
       (add_35_2_n_50));
  NOR2X4 add_35_2_g233(.A (add_35_2_n_22), .B (add_35_2_n_17), .Y
       (add_35_2_n_49));
  OR2XL add_35_2_g235(.A (add_35_2_n_16), .B (add_35_2_n_33), .Y
       (add_35_2_n_48));
  NAND2X1 add_35_2_g236(.A (add_35_2_n_39), .B (add_35_2_n_32), .Y
       (add_35_2_n_47));
  OAI21X1 add_35_2_g237(.A0 (add_35_2_n_27), .A1 (add_35_2_n_25), .B0
       (add_35_2_n_30), .Y (add_35_2_n_46));
  NOR2X2 add_35_2_g239(.A (add_35_2_n_2), .B (add_35_2_n_31), .Y
       (add_35_2_n_45));
  AOI2BB1X1 add_35_2_g240(.A0N (add_35_2_n_21), .A1N (add_35_2_n_28),
       .B0 (add_35_2_n_29), .Y (add_35_2_n_44));
  INVX1 add_35_2_g244(.A (add_35_2_n_39), .Y (add_35_2_n_40));
  NAND2X2 add_35_2_g245(.A (add_35_2_n_26), .B (add_35_2_n_19), .Y
       (add_35_2_n_38));
  NAND2X1 add_35_2_g246(.A (add_35_2_n_91), .B (add_35_2_n_19), .Y
       (add_35_2_n_43));
  NAND2BX1 add_35_2_g247(.AN (add_35_2_n_24), .B (add_35_2_n_18), .Y
       (add_35_2_n_42));
  NOR2X1 add_35_2_g248(.A (add_35_2_n_1), .B (add_35_2_n_22), .Y
       (add_35_2_n_37));
  NOR2X1 add_35_2_g249(.A (add_35_2_n_2), .B (add_35_2_n_20), .Y
       (add_35_2_n_41));
  NOR2X1 add_35_2_g250(.A (add_35_2_n_28), .B (add_35_2_n_16), .Y
       (add_35_2_n_39));
  INVX1 add_35_2_g254(.A (add_35_2_n_32), .Y (add_35_2_n_33));
  NOR2X1 add_35_2_g255(.A (add_35_2_n_18), .B (add_35_2_n_20), .Y
       (add_35_2_n_31));
  NAND2X1 add_35_2_g257(.A (add_35_2_n_30), .B (add_35_2_n_26), .Y
       (add_35_2_n_36));
  NOR2X1 add_35_2_g258(.A (add_35_2_n_29), .B (add_35_2_n_28), .Y
       (add_35_2_n_35));
  NAND2BX1 add_35_2_g259(.AN (add_35_2_n_16), .B (add_35_2_n_21), .Y
       (add_35_2_n_34));
  NOR2X2 add_35_2_g260(.A (add_35_2_n_24), .B (add_35_2_n_20), .Y
       (add_35_2_n_32));
  CLKINVX2 add_35_2_g261(.A (add_35_2_n_25), .Y (add_35_2_n_26));
  NAND2X1 add_35_2_g262(.A (in2[9]), .B (in2[8]), .Y (add_35_2_n_23));
  NAND2X2 add_35_2_g263(.A (in2[3]), .B (in1[3]), .Y (add_35_2_n_30));
  AND2X1 add_35_2_g265(.A (in2[7]), .B (in1[7]), .Y (add_35_2_n_29));
  NOR2X2 add_35_2_g266(.A (in2[7]), .B (in1[7]), .Y (add_35_2_n_28));
  NAND2X4 add_35_2_g267(.A (in2[2]), .B (in1[2]), .Y (add_35_2_n_27));
  NOR2X8 add_35_2_g268(.A (in2[3]), .B (in1[3]), .Y (add_35_2_n_25));
  NOR2X2 add_35_2_g269(.A (in2[4]), .B (in1[4]), .Y (add_35_2_n_24));
  NOR2X4 add_35_2_g271(.A (in2[1]), .B (in1[1]), .Y (add_35_2_n_22));
  NAND2X1 add_35_2_g273(.A (in2[6]), .B (in1[6]), .Y (add_35_2_n_21));
  NOR2X2 add_35_2_g274(.A (in2[5]), .B (in1[5]), .Y (add_35_2_n_20));
  NAND2X2 add_35_2_g275(.A (add_35_2_n_15), .B (add_35_2_n_14), .Y
       (add_35_2_n_19));
  NAND2X2 add_35_2_g276(.A (in2[4]), .B (in1[4]), .Y (add_35_2_n_18));
  NAND2X4 add_35_2_g277(.A (in2[0]), .B (in1[0]), .Y (add_35_2_n_17));
  NOR2X2 add_35_2_g278(.A (in2[6]), .B (in1[6]), .Y (add_35_2_n_16));
  CLKINVX2 add_35_2_g280(.A (in2[2]), .Y (add_35_2_n_15));
  CLKINVX2 add_35_2_g281(.A (in1[2]), .Y (add_35_2_n_14));
  INVXL add_35_2_g286(.A (in2[9]), .Y (add_35_2_n_13));
  INVX1 add_35_2_g287(.A (in2[8]), .Y (add_35_2_n_12));
  XNOR2X1 add_35_2_g2(.A (add_35_2_n_17), .B (add_35_2_n_37), .Y
       (out1[1]));
  NOR2BX1 add_35_2_g288(.AN (add_35_2_n_45), .B (add_35_2_n_59), .Y
       (add_35_2_n_10));
  CLKXOR2X1 add_35_2_g289(.A (add_35_2_n_43), .B (add_35_2_n_87), .Y
       (out1[2]));
  CLKXOR2X1 add_35_2_g290(.A (add_35_2_n_42), .B (add_35_2_n_95), .Y
       (out1[4]));
  XNOR2XL add_35_2_g291(.A (add_35_2_n_41), .B (add_35_2_n_61), .Y
       (out1[5]));
  CLKXOR2X1 add_35_2_g292(.A (add_35_2_n_36), .B (add_35_2_n_55), .Y
       (out1[3]));
  XNOR2XL add_35_2_g293(.A (add_35_2_n_35), .B (add_35_2_n_60), .Y
       (out1[7]));
  CLKXOR2X1 add_35_2_g294(.A (add_35_2_n_34), .B (add_35_2_n_10), .Y
       (out1[6]));
  NOR2BX1 add_35_2_g295(.AN (add_35_2_n_19), .B (add_35_2_n_88), .Y
       (add_35_2_n_3));
  AND2X1 add_35_2_g296(.A (in2[5]), .B (in1[5]), .Y (add_35_2_n_2));
  CLKAND2X6 add_35_2_g297(.A (in2[1]), .B (in1[1]), .Y (add_35_2_n_1));
  CLKXOR2X1 add_35_2_g298(.A (in2[0]), .B (in1[0]), .Y (out1[0]));
  BUFX2 add_35_2_fopt(.A (add_35_2_n_62), .Y (add_35_2_n_85));
  INVXL add_35_2_fopt299(.A (add_35_2_n_89), .Y (add_35_2_n_87));
  INVXL add_35_2_fopt300(.A (add_35_2_n_89), .Y (add_35_2_n_88));
  INVXL add_35_2_fopt301(.A (add_35_2_n_50), .Y (add_35_2_n_89));
  INVXL add_35_2_fopt302(.A (add_35_2_n_93), .Y (add_35_2_n_91));
  INVXL add_35_2_fopt303(.A (add_35_2_n_93), .Y (add_35_2_n_92));
  INVXL add_35_2_fopt304(.A (add_35_2_n_27), .Y (add_35_2_n_93));
  BUFX2 add_35_2_fopt305(.A (add_35_2_n_54), .Y (add_35_2_n_95));
endmodule


