`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Nov 17 2020 22:53:50 EST (Nov 18 2020 03:53:50 UTC)

module dut_Add_6U_1_4(in2, in1, out1);
  input [5:0] in2, in1;
  output [5:0] out1;
  wire [5:0] in2, in1;
  wire [5:0] out1;
  wire add_35_2_n_0, add_35_2_n_1, add_35_2_n_3, add_35_2_n_5,
       add_35_2_n_7, add_35_2_n_9;
  XNOR2X1 add_35_2_g168(.A (add_35_2_n_0), .B (add_35_2_n_9), .Y
       (out1[5]));
  ADDFX1 add_35_2_g169(.A (add_35_2_n_7), .B (in1[4]), .CI (in2[4]),
       .CO (add_35_2_n_9), .S (out1[4]));
  ADDFX1 add_35_2_g170(.A (add_35_2_n_5), .B (in1[3]), .CI (in2[3]),
       .CO (add_35_2_n_7), .S (out1[3]));
  ADDFX1 add_35_2_g171(.A (add_35_2_n_3), .B (in1[2]), .CI (in2[2]),
       .CO (add_35_2_n_5), .S (out1[2]));
  ADDFX1 add_35_2_g172(.A (add_35_2_n_1), .B (in1[1]), .CI (in2[1]),
       .CO (add_35_2_n_3), .S (out1[1]));
  ADDHX1 add_35_2_g173(.A (in2[0]), .B (in1[0]), .CO (add_35_2_n_1), .S
       (out1[0]));
  XNOR2X1 add_35_2_g174(.A (in2[5]), .B (in1[5]), .Y (add_35_2_n_0));
endmodule


