`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Nov 17 2020 22:52:51 EST (Nov 18 2020 03:52:51 UTC)

module dut_Add_11Ux8U_11U_4(in2, in1, out1);
  input [10:0] in2;
  input [7:0] in1;
  output [10:0] out1;
  wire [10:0] in2;
  wire [7:0] in1;
  wire [10:0] out1;
  wire add_35_2_n_0, add_35_2_n_1, add_35_2_n_2, add_35_2_n_3,
       add_35_2_n_4, add_35_2_n_5, add_35_2_n_6, add_35_2_n_7;
  wire add_35_2_n_8, add_35_2_n_9, add_35_2_n_10, add_35_2_n_11,
       add_35_2_n_12, add_35_2_n_13, add_35_2_n_14, add_35_2_n_15;
  wire add_35_2_n_16, add_35_2_n_18, add_35_2_n_20, add_35_2_n_23,
       add_35_2_n_24, add_35_2_n_26, add_35_2_n_27, add_35_2_n_28;
  wire add_35_2_n_31, add_35_2_n_32, add_35_2_n_33, add_35_2_n_36;
  XNOR2X1 add_35_2_g319(.A (in2[10]), .B (add_35_2_n_36), .Y
       (out1[10]));
  XNOR2X1 add_35_2_g320(.A (in2[9]), .B (add_35_2_n_33), .Y (out1[9]));
  NAND2BX1 add_35_2_g321(.AN (add_35_2_n_33), .B (in2[9]), .Y
       (add_35_2_n_36));
  XNOR2X1 add_35_2_g322(.A (in2[8]), .B (add_35_2_n_31), .Y (out1[8]));
  XNOR2X1 add_35_2_g323(.A (add_35_2_n_14), .B (add_35_2_n_32), .Y
       (out1[7]));
  NAND2BX1 add_35_2_g324(.AN (add_35_2_n_31), .B (in2[8]), .Y
       (add_35_2_n_33));
  OAI21X1 add_35_2_g325(.A0 (add_35_2_n_5), .A1 (add_35_2_n_27), .B0
       (add_35_2_n_1), .Y (add_35_2_n_32));
  AOI211XL add_35_2_g326(.A0 (add_35_2_n_12), .A1 (add_35_2_n_15), .B0
       (add_35_2_n_28), .C0 (add_35_2_n_9), .Y (add_35_2_n_31));
  XNOR2X1 add_35_2_g327(.A (add_35_2_n_11), .B (add_35_2_n_27), .Y
       (out1[6]));
  XNOR2X1 add_35_2_g328(.A (add_35_2_n_10), .B (add_35_2_n_26), .Y
       (out1[5]));
  OAI2BB1X1 add_35_2_g329(.A0N (add_35_2_n_12), .A1N (add_35_2_n_24),
       .B0 (add_35_2_n_6), .Y (add_35_2_n_28));
  NOR2X1 add_35_2_g330(.A (add_35_2_n_15), .B (add_35_2_n_24), .Y
       (add_35_2_n_27));
  OAI2BB1X1 add_35_2_g331(.A0N (add_35_2_n_8), .A1N (add_35_2_n_23),
       .B0 (add_35_2_n_2), .Y (add_35_2_n_26));
  XNOR2X1 add_35_2_g332(.A (add_35_2_n_13), .B (add_35_2_n_23), .Y
       (out1[4]));
  NOR3BX1 add_35_2_g333(.AN (add_35_2_n_23), .B (add_35_2_n_4), .C
       (add_35_2_n_7), .Y (add_35_2_n_24));
  ADDFX1 add_35_2_g334(.A (add_35_2_n_20), .B (in1[3]), .CI (in2[3]),
       .CO (add_35_2_n_23), .S (out1[3]));
  ADDFX1 add_35_2_g335(.A (add_35_2_n_18), .B (in1[2]), .CI (in2[2]),
       .CO (add_35_2_n_20), .S (out1[2]));
  ADDFX1 add_35_2_g336(.A (add_35_2_n_16), .B (in1[1]), .CI (in2[1]),
       .CO (add_35_2_n_18), .S (out1[1]));
  ADDHX1 add_35_2_g337(.A (in2[0]), .B (in1[0]), .CO (add_35_2_n_16),
       .S (out1[0]));
  OAI21X1 add_35_2_g338(.A0 (add_35_2_n_2), .A1 (add_35_2_n_4), .B0
       (add_35_2_n_3), .Y (add_35_2_n_15));
  NAND2BX1 add_35_2_g339(.AN (add_35_2_n_0), .B (add_35_2_n_6), .Y
       (add_35_2_n_14));
  NAND2X1 add_35_2_g340(.A (add_35_2_n_2), .B (add_35_2_n_8), .Y
       (add_35_2_n_13));
  NOR2X1 add_35_2_g341(.A (add_35_2_n_0), .B (add_35_2_n_5), .Y
       (add_35_2_n_12));
  NOR2BX1 add_35_2_g342(.AN (add_35_2_n_1), .B (add_35_2_n_5), .Y
       (add_35_2_n_11));
  NAND2BX1 add_35_2_g343(.AN (add_35_2_n_4), .B (add_35_2_n_3), .Y
       (add_35_2_n_10));
  NOR2X1 add_35_2_g344(.A (add_35_2_n_1), .B (add_35_2_n_0), .Y
       (add_35_2_n_9));
  INVX1 add_35_2_g345(.A (add_35_2_n_7), .Y (add_35_2_n_8));
  NOR2X1 add_35_2_g346(.A (in2[4]), .B (in1[4]), .Y (add_35_2_n_7));
  NAND2X1 add_35_2_g347(.A (in2[7]), .B (in1[7]), .Y (add_35_2_n_6));
  NOR2X1 add_35_2_g348(.A (in2[6]), .B (in1[6]), .Y (add_35_2_n_5));
  NOR2X1 add_35_2_g349(.A (in2[5]), .B (in1[5]), .Y (add_35_2_n_4));
  NAND2X1 add_35_2_g350(.A (in2[5]), .B (in1[5]), .Y (add_35_2_n_3));
  NAND2X1 add_35_2_g351(.A (in2[4]), .B (in1[4]), .Y (add_35_2_n_2));
  NAND2X1 add_35_2_g352(.A (in2[6]), .B (in1[6]), .Y (add_35_2_n_1));
  NOR2X1 add_35_2_g353(.A (in2[7]), .B (in1[7]), .Y (add_35_2_n_0));
endmodule


