`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Nov 19 2020 23:21:02 EST (Nov 20 2020 04:21:02 UTC)

module dut_NotBit_1U_2_4(in1, out1);
  input in1;
  output out1;
  wire in1;
  wire out1;
  INVX1 g2(.A (in1), .Y (out1));
endmodule


