`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Nov 16 2020 23:44:41 EST (Nov 17 2020 04:44:41 UTC)

module dut_Mul_8Ux3U_11U_4(in2, in1, out1);
  input [7:0] in2;
  input [2:0] in1;
  output [10:0] out1;
  wire [7:0] in2;
  wire [2:0] in1;
  wire [10:0] out1;
  wire mul_34_8_n_0, mul_34_8_n_1, mul_34_8_n_2, mul_34_8_n_3,
       mul_34_8_n_4, mul_34_8_n_5, mul_34_8_n_6, mul_34_8_n_7;
  wire mul_34_8_n_8, mul_34_8_n_9, mul_34_8_n_10, mul_34_8_n_11,
       mul_34_8_n_12, mul_34_8_n_13, mul_34_8_n_14, mul_34_8_n_15;
  wire mul_34_8_n_16, mul_34_8_n_17, mul_34_8_n_18, mul_34_8_n_19,
       mul_34_8_n_20, mul_34_8_n_22, mul_34_8_n_23, mul_34_8_n_24;
  wire mul_34_8_n_25, mul_34_8_n_26, mul_34_8_n_27, mul_34_8_n_29,
       mul_34_8_n_30, mul_34_8_n_31, mul_34_8_n_32, mul_34_8_n_33;
  wire mul_34_8_n_34, mul_34_8_n_35, mul_34_8_n_36, mul_34_8_n_37,
       mul_34_8_n_38, mul_34_8_n_39, mul_34_8_n_40, mul_34_8_n_41;
  wire mul_34_8_n_42, mul_34_8_n_43, mul_34_8_n_44, mul_34_8_n_45,
       mul_34_8_n_46, mul_34_8_n_47, mul_34_8_n_48, mul_34_8_n_49;
  wire mul_34_8_n_50, mul_34_8_n_51, mul_34_8_n_52, mul_34_8_n_53,
       mul_34_8_n_54, mul_34_8_n_55, mul_34_8_n_56, mul_34_8_n_57;
  wire mul_34_8_n_58, mul_34_8_n_59, mul_34_8_n_60, mul_34_8_n_61,
       mul_34_8_n_62, mul_34_8_n_64, mul_34_8_n_65, mul_34_8_n_66;
  wire mul_34_8_n_68, mul_34_8_n_70, mul_34_8_n_71, mul_34_8_n_72,
       mul_34_8_n_74, mul_34_8_n_76;
  OAI21X1 mul_34_8_g652(.A0 (mul_34_8_n_33), .A1 (mul_34_8_n_0), .B0
       (mul_34_8_n_34), .Y (out1[10]));
  XNOR2X1 mul_34_8_g653(.A (mul_34_8_n_37), .B (mul_34_8_n_0), .Y
       (out1[9]));
  XNOR2X1 mul_34_8_g656(.A (mul_34_8_n_61), .B (mul_34_8_n_74), .Y
       (out1[8]));
  XNOR2X1 mul_34_8_g657(.A (mul_34_8_n_60), .B (mul_34_8_n_76), .Y
       (out1[7]));
  AOI21X1 mul_34_8_g658(.A0 (mul_34_8_n_54), .A1 (mul_34_8_n_72), .B0
       (mul_34_8_n_55), .Y (mul_34_8_n_76));
  XNOR2X1 mul_34_8_g659(.A (mul_34_8_n_59), .B (mul_34_8_n_72), .Y
       (out1[6]));
  OAI211X1 mul_34_8_g660(.A0 (mul_34_8_n_56), .A1 (mul_34_8_n_70), .B0
       (mul_34_8_n_66), .C0 (mul_34_8_n_49), .Y (mul_34_8_n_74));
  XNOR2X1 mul_34_8_g661(.A (mul_34_8_n_57), .B (mul_34_8_n_71), .Y
       (out1[5]));
  NAND2X1 mul_34_8_g662(.A (mul_34_8_n_64), .B (mul_34_8_n_70), .Y
       (mul_34_8_n_72));
  AOI21X1 mul_34_8_g663(.A0 (mul_34_8_n_48), .A1 (mul_34_8_n_68), .B0
       (mul_34_8_n_52), .Y (mul_34_8_n_71));
  NAND3X1 mul_34_8_g664(.A (mul_34_8_n_50), .B (mul_34_8_n_48), .C
       (mul_34_8_n_68), .Y (mul_34_8_n_70));
  XNOR2X1 mul_34_8_g665(.A (mul_34_8_n_58), .B (mul_34_8_n_68), .Y
       (out1[4]));
  ADDFX1 mul_34_8_g666(.A (mul_34_8_n_62), .B (mul_34_8_n_35), .CI
       (mul_34_8_n_29), .CO (mul_34_8_n_68), .S (out1[3]));
  AOI21X1 mul_34_8_g667(.A0 (mul_34_8_n_55), .A1 (mul_34_8_n_51), .B0
       (mul_34_8_n_65), .Y (mul_34_8_n_66));
  NOR2X1 mul_34_8_g668(.A (mul_34_8_n_56), .B (mul_34_8_n_64), .Y
       (mul_34_8_n_65));
  AOI21X1 mul_34_8_g669(.A0 (mul_34_8_n_52), .A1 (mul_34_8_n_50), .B0
       (mul_34_8_n_53), .Y (mul_34_8_n_64));
  ADDFX1 mul_34_8_g670(.A (mul_34_8_n_25), .B (mul_34_8_n_20), .CI
       (mul_34_8_n_30), .CO (mul_34_8_n_62), .S (out1[2]));
  NAND2BX1 mul_34_8_g671(.AN (mul_34_8_n_47), .B (mul_34_8_n_46), .Y
       (mul_34_8_n_61));
  AND2XL mul_34_8_g672(.A (mul_34_8_n_49), .B (mul_34_8_n_51), .Y
       (mul_34_8_n_60));
  NAND2BX1 mul_34_8_g673(.AN (mul_34_8_n_55), .B (mul_34_8_n_54), .Y
       (mul_34_8_n_59));
  NAND2BX1 mul_34_8_g674(.AN (mul_34_8_n_52), .B (mul_34_8_n_48), .Y
       (mul_34_8_n_58));
  NOR2BX1 mul_34_8_g675(.AN (mul_34_8_n_50), .B (mul_34_8_n_53), .Y
       (mul_34_8_n_57));
  NAND2X1 mul_34_8_g676(.A (mul_34_8_n_51), .B (mul_34_8_n_54), .Y
       (mul_34_8_n_56));
  NOR2X1 mul_34_8_g677(.A (mul_34_8_n_44), .B (mul_34_8_n_41), .Y
       (mul_34_8_n_55));
  NAND2X1 mul_34_8_g678(.A (mul_34_8_n_44), .B (mul_34_8_n_41), .Y
       (mul_34_8_n_54));
  NOR2X1 mul_34_8_g679(.A (mul_34_8_n_42), .B (mul_34_8_n_45), .Y
       (mul_34_8_n_53));
  NOR2X1 mul_34_8_g680(.A (mul_34_8_n_36), .B (mul_34_8_n_43), .Y
       (mul_34_8_n_52));
  NAND2X1 mul_34_8_g681(.A (mul_34_8_n_40), .B (mul_34_8_n_39), .Y
       (mul_34_8_n_51));
  NAND2X1 mul_34_8_g682(.A (mul_34_8_n_42), .B (mul_34_8_n_45), .Y
       (mul_34_8_n_50));
  OR2XL mul_34_8_g683(.A (mul_34_8_n_40), .B (mul_34_8_n_39), .Y
       (mul_34_8_n_49));
  NAND2X1 mul_34_8_g684(.A (mul_34_8_n_36), .B (mul_34_8_n_43), .Y
       (mul_34_8_n_48));
  NOR2X1 mul_34_8_g685(.A (mul_34_8_n_27), .B (mul_34_8_n_38), .Y
       (mul_34_8_n_47));
  NAND2X1 mul_34_8_g686(.A (mul_34_8_n_27), .B (mul_34_8_n_38), .Y
       (mul_34_8_n_46));
  ADDFX1 mul_34_8_g687(.A (mul_34_8_n_17), .B (mul_34_8_n_13), .CI
       (mul_34_8_n_14), .CO (mul_34_8_n_44), .S (mul_34_8_n_45));
  ADDFX1 mul_34_8_g688(.A (mul_34_8_n_18), .B (mul_34_8_n_3), .CI
       (mul_34_8_n_2), .CO (mul_34_8_n_42), .S (mul_34_8_n_43));
  ADDFX1 mul_34_8_g689(.A (mul_34_8_n_5), .B (mul_34_8_n_15), .CI
       (mul_34_8_n_16), .CO (mul_34_8_n_40), .S (mul_34_8_n_41));
  ADDFX1 mul_34_8_g690(.A (mul_34_8_n_6), .B (mul_34_8_n_1), .CI
       (mul_34_8_n_4), .CO (mul_34_8_n_38), .S (mul_34_8_n_39));
  NOR2BX1 mul_34_8_g691(.AN (mul_34_8_n_34), .B (mul_34_8_n_33), .Y
       (mul_34_8_n_37));
  OA22X1 mul_34_8_g692(.A0 (mul_34_8_n_10), .A1 (mul_34_8_n_31), .B0
       (mul_34_8_n_9), .B1 (mul_34_8_n_8), .Y (mul_34_8_n_36));
  XNOR2X1 mul_34_8_g693(.A (mul_34_8_n_10), .B (mul_34_8_n_32), .Y
       (mul_34_8_n_35));
  NAND2BX1 mul_34_8_g694(.AN (mul_34_8_n_24), .B (mul_34_8_n_26), .Y
       (mul_34_8_n_34));
  NOR2BX1 mul_34_8_g695(.AN (mul_34_8_n_24), .B (mul_34_8_n_26), .Y
       (mul_34_8_n_33));
  ADDHX1 mul_34_8_g696(.A (mul_34_8_n_9), .B (mul_34_8_n_8), .CO
       (mul_34_8_n_31), .S (mul_34_8_n_32));
  ADDHX1 mul_34_8_g697(.A (mul_34_8_n_19), .B (mul_34_8_n_7), .CO
       (mul_34_8_n_29), .S (mul_34_8_n_30));
  AOI21X1 mul_34_8_g698(.A0 (mul_34_8_n_12), .A1 (mul_34_8_n_11), .B0
       (mul_34_8_n_25), .Y (out1[1]));
  XNOR2X1 mul_34_8_g699(.A (mul_34_8_n_23), .B (mul_34_8_n_22), .Y
       (mul_34_8_n_27));
  NOR2X1 mul_34_8_g700(.A (mul_34_8_n_23), .B (mul_34_8_n_22), .Y
       (mul_34_8_n_26));
  NOR2X1 mul_34_8_g701(.A (mul_34_8_n_12), .B (mul_34_8_n_11), .Y
       (mul_34_8_n_25));
  AND2XL mul_34_8_g702(.A (in2[0]), .B (in1[0]), .Y (out1[0]));
  AND2XL mul_34_8_g703(.A (in2[0]), .B (in1[2]), .Y (mul_34_8_n_20));
  NAND2X1 mul_34_8_g704(.A (in2[7]), .B (in1[2]), .Y (mul_34_8_n_24));
  AND2XL mul_34_8_g705(.A (in2[1]), .B (in1[1]), .Y (mul_34_8_n_19));
  NAND2X1 mul_34_8_g706(.A (in2[2]), .B (in1[2]), .Y (mul_34_8_n_18));
  NAND2X1 mul_34_8_g707(.A (in2[3]), .B (in1[2]), .Y (mul_34_8_n_17));
  NAND2X1 mul_34_8_g708(.A (in2[6]), .B (in1[2]), .Y (mul_34_8_n_23));
  NAND2X1 mul_34_8_g709(.A (in2[7]), .B (in1[1]), .Y (mul_34_8_n_22));
  NAND2X1 mul_34_8_g710(.A (in2[5]), .B (in1[1]), .Y (mul_34_8_n_16));
  NAND2X1 mul_34_8_g711(.A (in2[6]), .B (in1[0]), .Y (mul_34_8_n_15));
  NAND2X1 mul_34_8_g712(.A (in2[4]), .B (in1[1]), .Y (mul_34_8_n_14));
  NAND2X1 mul_34_8_g713(.A (in2[5]), .B (in1[0]), .Y (mul_34_8_n_13));
  NAND2X1 mul_34_8_g714(.A (in2[0]), .B (in1[1]), .Y (mul_34_8_n_12));
  NAND2X1 mul_34_8_g715(.A (in2[1]), .B (in1[0]), .Y (mul_34_8_n_11));
  AND2XL mul_34_8_g716(.A (in2[2]), .B (in1[0]), .Y (mul_34_8_n_7));
  NAND2X1 mul_34_8_g717(.A (in2[5]), .B (in1[2]), .Y (mul_34_8_n_6));
  NAND2X1 mul_34_8_g718(.A (in2[4]), .B (in1[2]), .Y (mul_34_8_n_5));
  NAND2X1 mul_34_8_g719(.A (in2[1]), .B (in1[2]), .Y (mul_34_8_n_10));
  NAND2X1 mul_34_8_g720(.A (in2[2]), .B (in1[1]), .Y (mul_34_8_n_9));
  NAND2X1 mul_34_8_g721(.A (in2[6]), .B (in1[1]), .Y (mul_34_8_n_4));
  NAND2X1 mul_34_8_g722(.A (in2[4]), .B (in1[0]), .Y (mul_34_8_n_3));
  NAND2X1 mul_34_8_g723(.A (in2[3]), .B (in1[1]), .Y (mul_34_8_n_2));
  NAND2X1 mul_34_8_g724(.A (in2[3]), .B (in1[0]), .Y (mul_34_8_n_8));
  NAND2X1 mul_34_8_g725(.A (in2[7]), .B (in1[0]), .Y (mul_34_8_n_1));
  AOI21X1 mul_34_8_g726(.A0 (mul_34_8_n_46), .A1 (mul_34_8_n_74), .B0
       (mul_34_8_n_47), .Y (mul_34_8_n_0));
endmodule


