// Generated by stratus_hls 17.20-p100  (88533.190925)
// Tue Nov 17 22:53:07 2020
// from dut.cc
#ifndef CYNTH_PART_dut_dut_RAM_8X8_1_h
#define CYNTH_PART_dut_dut_RAM_8X8_1_h

#include "systemc.h"
/* Include declarations of instantiated parts. */


/* Declaration of the synthesized module. */
struct dut_RAM_8X8_1 : public sc_module {
  sc_in<sc_uint<8> > DIN;
  sc_in<sc_uint<1> > CE;
  sc_in<sc_uint<1> > RW;
  sc_in<sc_uint<3> > in1;
  sc_out<sc_uint<8> > out1;
  sc_in<bool > clk;
  dut_RAM_8X8_1( sc_module_name name );
  SC_HAS_PROCESS(dut_RAM_8X8_1);
  sc_uint<8> mem[8];
  void dut_RAM_8X8_1_thread_1();
};

#endif
