`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Nov 17 2020 14:06:20 EST (Nov 17 2020 19:06:20 UTC)

module dut_Add_7Sx2S_8S_1(in2, in1, out1);
  input [6:0] in2;
  input [1:0] in1;
  output [7:0] out1;
  wire [6:0] in2;
  wire [1:0] in1;
  wire [7:0] out1;
  wire add_35_2_n_1, add_35_2_n_5, add_35_2_n_10, add_35_2_n_11,
       add_35_2_n_12, add_35_2_n_13, add_35_2_n_14, add_35_2_n_15;
  wire add_35_2_n_16, add_35_2_n_17, add_35_2_n_18, add_35_2_n_19,
       add_35_2_n_20, add_35_2_n_21, add_35_2_n_22, add_35_2_n_23;
  wire add_35_2_n_24, add_35_2_n_25, add_35_2_n_26, add_35_2_n_27,
       add_35_2_n_28, add_35_2_n_29, add_35_2_n_30, add_35_2_n_31;
  wire add_35_2_n_32, add_35_2_n_33, add_35_2_n_34, add_35_2_n_35,
       add_35_2_n_36, add_35_2_n_37, add_35_2_n_38, add_35_2_n_39;
  wire add_35_2_n_40, add_35_2_n_41, add_35_2_n_42, add_35_2_n_43,
       add_35_2_n_44, add_35_2_n_45, add_35_2_n_46, add_35_2_n_47;
  wire add_35_2_n_61, add_35_2_n_62, add_35_2_n_63, add_35_2_n_67,
       add_35_2_n_68, add_35_2_n_69, add_35_2_n_70, add_35_2_n_71;
  wire add_35_2_n_72, add_35_2_n_74;
  MXI2X1 add_35_2_g141(.A (add_35_2_n_31), .B (add_35_2_n_32), .S0
       (add_35_2_n_46), .Y (out1[5]));
  NOR2BX1 add_35_2_g142(.AN (add_35_2_n_40), .B (add_35_2_n_44), .Y
       (out1[7]));
  NOR2X1 add_35_2_g143(.A (add_35_2_n_36), .B (add_35_2_n_5), .Y
       (add_35_2_n_47));
  NOR2X1 add_35_2_g144(.A (add_35_2_n_17), .B (add_35_2_n_45), .Y
       (add_35_2_n_46));
  NOR2X1 add_35_2_g148(.A (add_35_2_n_20), .B (add_35_2_n_42), .Y
       (add_35_2_n_45));
  NOR2X1 add_35_2_g149(.A (add_35_2_n_37), .B (add_35_2_n_42), .Y
       (add_35_2_n_44));
  NOR2BX1 add_35_2_g150(.AN (add_35_2_n_11), .B (add_35_2_n_1), .Y
       (add_35_2_n_43));
  NOR2X4 add_35_2_g152(.A (add_35_2_n_35), .B (add_35_2_n_41), .Y
       (add_35_2_n_42));
  NOR2X4 add_35_2_g154(.A (add_35_2_n_27), .B (add_35_2_n_39), .Y
       (add_35_2_n_41));
  AOI21X1 add_35_2_g155(.A0 (add_35_2_n_14), .A1 (add_35_2_n_36), .B0
       (add_35_2_n_22), .Y (add_35_2_n_40));
  NOR2X4 add_35_2_g156(.A (add_35_2_n_19), .B (add_35_2_n_38), .Y
       (add_35_2_n_39));
  NOR2X4 add_35_2_g158(.A (add_35_2_n_15), .B (add_35_2_n_23), .Y
       (add_35_2_n_38));
  NAND2X1 add_35_2_g160(.A (add_35_2_n_14), .B (add_35_2_n_33), .Y
       (add_35_2_n_37));
  OAI21X1 add_35_2_g161(.A0 (add_35_2_n_16), .A1 (add_35_2_n_21), .B0
       (add_35_2_n_24), .Y (add_35_2_n_36));
  OAI21X2 add_35_2_g162(.A0 (add_35_2_n_11), .A1 (add_35_2_n_12), .B0
       (add_35_2_n_25), .Y (add_35_2_n_35));
  NAND2BX1 add_35_2_g164(.AN (add_35_2_n_22), .B (add_35_2_n_14), .Y
       (add_35_2_n_34));
  NOR2X1 add_35_2_g166(.A (add_35_2_n_21), .B (add_35_2_n_20), .Y
       (add_35_2_n_33));
  INVX1 add_35_2_g167(.A (add_35_2_n_31), .Y (add_35_2_n_32));
  NOR2BX1 add_35_2_g168(.AN (add_35_2_n_24), .B (add_35_2_n_21), .Y
       (add_35_2_n_31));
  NAND2X1 add_35_2_g170(.A (add_35_2_n_11), .B (add_35_2_n_18), .Y
       (add_35_2_n_30));
  NOR2X1 add_35_2_g172(.A (add_35_2_n_17), .B (add_35_2_n_20), .Y
       (add_35_2_n_29));
  NOR2X1 add_35_2_g173(.A (add_35_2_n_19), .B (add_35_2_n_23), .Y
       (add_35_2_n_28));
  NAND2X2 add_35_2_g174(.A (add_35_2_n_13), .B (add_35_2_n_18), .Y
       (add_35_2_n_27));
  NAND2X1 add_35_2_g176(.A (add_35_2_n_25), .B (add_35_2_n_13), .Y
       (add_35_2_n_26));
  NAND2X1 add_35_2_g178(.A (in2[3]), .B (in1[1]), .Y (add_35_2_n_25));
  NAND2X1 add_35_2_g179(.A (in2[5]), .B (add_35_2_n_70), .Y
       (add_35_2_n_24));
  NOR2X8 add_35_2_g180(.A (in2[1]), .B (in1[1]), .Y (add_35_2_n_23));
  NOR2X1 add_35_2_g181(.A (in2[6]), .B (add_35_2_n_67), .Y
       (add_35_2_n_22));
  NOR2X1 add_35_2_g182(.A (in2[5]), .B (in1[1]), .Y (add_35_2_n_21));
  NOR2X1 add_35_2_g183(.A (in2[4]), .B (in1[1]), .Y (add_35_2_n_20));
  INVX1 add_35_2_g185(.A (add_35_2_n_16), .Y (add_35_2_n_17));
  CLKINVX2 add_35_2_g186(.A (add_35_2_n_12), .Y (add_35_2_n_13));
  NOR2X2 add_35_2_g187(.A (add_35_2_n_10), .B (add_35_2_n_71), .Y
       (add_35_2_n_19));
  NAND2X4 add_35_2_g188(.A (add_35_2_n_72), .B (add_35_2_n_74), .Y
       (add_35_2_n_18));
  NAND2X1 add_35_2_g189(.A (in2[4]), .B (add_35_2_n_70), .Y
       (add_35_2_n_16));
  NAND2X4 add_35_2_g190(.A (in2[0]), .B (in1[0]), .Y (add_35_2_n_15));
  NAND2X1 add_35_2_g191(.A (in2[6]), .B (add_35_2_n_68), .Y
       (add_35_2_n_14));
  NOR2X8 add_35_2_g192(.A (in2[3]), .B (in1[1]), .Y (add_35_2_n_12));
  NAND2X2 add_35_2_g193(.A (in2[2]), .B (in1[1]), .Y (add_35_2_n_11));
  CLKINVX3 add_35_2_g194(.A (in2[1]), .Y (add_35_2_n_10));
  XNOR2X1 add_35_2_g2(.A (add_35_2_n_15), .B (add_35_2_n_28), .Y
       (out1[1]));
  XOR2XL add_35_2_g198(.A (add_35_2_n_34), .B (add_35_2_n_47), .Y
       (out1[6]));
  NOR2BX2 add_35_2_g199(.AN (add_35_2_n_33), .B (add_35_2_n_42), .Y
       (add_35_2_n_5));
  CLKXOR2X1 add_35_2_g200(.A (add_35_2_n_30), .B (add_35_2_n_61), .Y
       (out1[2]));
  XNOR2XL add_35_2_g201(.A (add_35_2_n_29), .B (add_35_2_n_42), .Y
       (out1[4]));
  CLKXOR2X1 add_35_2_g202(.A (add_35_2_n_26), .B (add_35_2_n_43), .Y
       (out1[3]));
  NOR2BX1 add_35_2_g203(.AN (add_35_2_n_18), .B (add_35_2_n_62), .Y
       (add_35_2_n_1));
  XOR2XL add_35_2_g204(.A (in2[0]), .B (in1[0]), .Y (out1[0]));
  INVXL add_35_2_fopt(.A (add_35_2_n_63), .Y (add_35_2_n_61));
  INVXL add_35_2_fopt205(.A (add_35_2_n_63), .Y (add_35_2_n_62));
  INVXL add_35_2_fopt206(.A (add_35_2_n_39), .Y (add_35_2_n_63));
  INVXL add_35_2_fopt207(.A (add_35_2_n_69), .Y (add_35_2_n_67));
  INVXL add_35_2_fopt208(.A (add_35_2_n_69), .Y (add_35_2_n_68));
  INVXL add_35_2_fopt209(.A (add_35_2_n_70), .Y (add_35_2_n_69));
  CLKINVX1 add_35_2_fopt210(.A (add_35_2_n_71), .Y (add_35_2_n_70));
  CLKINVX2 add_35_2_fopt211(.A (in1[1]), .Y (add_35_2_n_71));
  CLKINVX4 add_35_2_fopt212(.A (in1[1]), .Y (add_35_2_n_72));
  CLKINVX4 add_35_2_fopt213(.A (in2[2]), .Y (add_35_2_n_74));
endmodule


