`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Nov 17 2020 14:07:06 EST (Nov 17 2020 19:07:06 UTC)

module dut_Equal_6Ux3U_1U_4(in2, in1, out1);
  input [5:0] in2;
  input [2:0] in1;
  output out1;
  wire [5:0] in2;
  wire [2:0] in1;
  wire out1;
  wire n_0, n_1, n_2, n_3;
  NOR3X1 g39(.A (n_3), .B (in2[4]), .C (in2[3]), .Y (out1));
  NAND4BX1 g40(.AN (in2[5]), .B (n_1), .C (n_0), .D (n_2), .Y (n_3));
  XNOR2X1 g41(.A (in2[2]), .B (in1[2]), .Y (n_2));
  XNOR2X1 g43(.A (in2[1]), .B (in1[1]), .Y (n_1));
  XNOR2X1 g42(.A (in2[0]), .B (in1[0]), .Y (n_0));
endmodule

